### ISSUE TITLE
可以调整当前图片与前后两张图片的高度差吗

### ISSUE THREAD

**Issue by hehongxiang95** [xiaohaibin/XBanner#101]
可以调整当前图片与前后两张图片的高度差吗

**Comment by xiaohaibin** [comment]
可以，具体看下文档和demo哈




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2019年06月01日 00:00，hehongxiang95 写道：

可以调整当前图片与前后两张图片的高度差吗

**Comment by faith-hb** [comment]
> 可以，具体看下文档和demo哈 | | 萧海斌 邮箱：xhb_199409@163.com | 签名由 网易邮箱大师 定制 在2019年06月01日 00:00，hehongxiang95 写道： 可以调整当前图片与前后两张图片的高度差吗 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

找不到啊
