### ISSUE TITLE
使用ClipChildrenMode模式，显示的都是最后一张图片

### ISSUE THREAD

**Issue by fjyuqiang** [xiaohaibin/XBanner#102]
version：1.6.7

question:使用一屏多图模式，显示的都是最后一张图，加载使用的Glide 4.9，是必须要像demo中建立bean类吗？

方法代码如下：
    private void initBanner() {
//        List<TuchongEntity.FeedListBean.EntryBean> data = new ArrayList<>();
        List<CustomViewsInfo> pictures = new ArrayList<>();

        pictures.add(new CustomViewsInfo("https://ss3.bdstatic.com/70cFv8Sh_Q1YnxGkpoWK1HF6hhy/it/u=3257674913,1564885286&fm=15&gp=0.jpg"));
        pictures.add(new CustomViewsInfo("https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1559490675307&di=8b9e0ada066a1c76d69faec0639148f5&imgtype=0&src=http%3A%2F%2Fimage.game.uc.cn%2F2016%2F7%2F26%2F13830299.png"));
        pictures.add(new CustomViewsInfo("https://ss3.bdstatic.com/70cFv8Sh_Q1YnxGkpoWK1HF6hhy/it/u=4204284744,3040278001&fm=11&gp=0.jpg"));
        pictures.add(new CustomViewsInfo("https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1559490758326&di=70d99c6c55e4d962bcb316777cb07348&imgtype=0&src=http%3A%2F%2Fimage.9game.cn%2F2018%2F11%2F8%2F31308897.jpg"));
        pictures.add(new CustomViewsInfo("https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=2629042691,1244851139&fm=11&gp=0.jpg"));

        mXBanner.loadImage(new XBanner.XBannerAdapter() {
            @Override
            public void loadBanner(XBanner banner, Object model, View view, int position) {

                //1、此处使用的Glide加载图片，可自行替换自己项目中的图片加载框架
                //2、返回的图片路径为Object类型，你只需要强转成你传输的类型就行，切记不要胡乱强转！
                for (CustomViewsInfo customViewsInfo: pictures)
                ImageLoader.loadRoundImage((ImageView) view, customViewsInfo.getXBannerUrl(), 8);
            }
        });

        //图片的点击监听
        mXBanner.setOnItemClickListener(new XBanner.OnItemClickListener() {
            @Override
            public void onItemClick(XBanner banner, Object model, View view, int position) {
                toast("点击了" + position + "张图片");
            }
        });

        //刷新数据之后，需要重新设置是否支持自动轮播
        mXBanner.setAutoPlayAble(pictures.size() > 1);
        mXBanner.setIsClipChildrenMode(true);
        //添加轮播图片数据（图片数据不局限于网络图片、本地资源文件、View 都可以）,刷新数据也是调用该方法
        mXBanner.setBannerData(R.layout.xbanner_item_image, pictures);

    }

**Comment by xiaohaibin** [comment]
![image](https://user-images.githubusercontent.com/11681218/58854225-4118b000-86cf-11e9-888d-963f4a6380f9.png)
为啥图片加载里面还要弄个循环？

**Comment by fjyuqiang** [comment]
已经解决了
