### ISSUE TITLE
两个问题

### ISSUE THREAD

**Issue by bananaskin2019** [xiaohaibin/XBanner#105]
第一个：
banner.setBannerData(R.layout.item_banner,bannerList);
第一次设置空list，
刷新数据后重新setBannerData会出现空白，
图片只会在手指切换的时候出现，不到1秒又变空白。
第二个：
按道理说一根手指滑动banner是滑不完一张图片的
我用两根手指来滑，保持至少有一根手指触摸在图片上
当两根手指滑完一张图片时app直接卡死。

**Comment by xiaohaibin** [comment]
版本、机型、
滑动跟几根手指滑动没有关系的

**Comment by bananaskin2019** [comment]
首先感谢作者的回复，回复速度很快。

xbanner版本：1.6.7
手机型号：小米 note3
Android版本：8.1.0

第二个问题，我下了sample运行，在ListViewActivity中获取的数据我截取了一下
data =   data.subList(0,4);
mXBanner.setAutoPlayAble(data.size() > 1);
mXBanner.setBannerData(data);

一根手指快速滑是没问题
然后就是按我说的两根手指滑完一张图，这边滑完就直接卡死了。(这个多测几下)

![QQ图片20190608150427](https://user-images.githubusercontent.com/49992807/59143642-6d01a180-89ff-11e9-9609-80b5e9113dc9.png)

**Comment by xiaohaibin** [comment]
问题一已修复，问题二我这边重试多次未复现，添加了一点代码，你在1.6.8版本再试试看是否重现

**Comment by bananaskin2019** [comment]
问题二解决了。
    问题一这块，
    第一次设置空List之后 xml属性isAutoPlay = true就失效了，再刷新数据也不开启。
    我看了一下局部代码

        if(mViews.isEmpty()){
        mIsAutoPlay = false;
        mIsClipChildrenMode = false;
        }

    是不是需要加个else判断

    //用户xml设置的isAutoPlay值
    boolean autoPlay 

        if(mViews.isEmpty()){
        mIsAutoPlay = false;
        mIsClipChildrenMode = false;
        }else{
        mIsAutoPlay = autoPlay;
        //...
        }

    然后代码setAutoPlayAble可以修改其属性：

    public void setAutoPlayAble(boolean mAutoPlayAble) {
        autoPlay = mAutoPlayAble;
        this.mIsAutoPlay = mAutoPlayAble;
        //...
    }

**Comment by xiaohaibin** [comment]
刷新数据之后要自己手动设置开启，看demo哈




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2019年06月11日 00:02，bananaskin2019 写道：

问题二解决了。
问题一这块，
第一次设置空List之后 xml属性isAutoPlay = true就失效了，再刷新数据也不开启。
我看了一下局部代码

    if(mViews.isEmpty()){

    mIsAutoPlay = false;

    mIsClipChildrenMode = false;

    }



是不是需要加个else判断



//用户xml设置的isAutoPlay值

boolean autoPlay 



    if(mViews.isEmpty()){

    mIsAutoPlay = false;

    mIsClipChildrenMode = false;

    }else{

    mIsAutoPlay = autoPlay;

    //...

    }



然后代码setAutoPlayAble可以修改其属性：



public void setAutoPlayAble(boolean mAutoPlayAble) {

    autoPlay = mAutoPlayAble;

    this.mIsAutoPlay = mAutoPlayAble;

    //...

}

**Comment by xiaohaibin** [comment]
//刷新数据之后，需要重新设置是否支持自动轮播
                        mBanner.setAutoPlayAble(data.size() > 1);
                        mBanner.setBannerData(data);

**Comment by bananaskin2019** [comment]
好的，这样的话这个问题可以关闭了
