### ISSUE TITLE
Points

### ISSUE THREAD

**Issue by qitian134** [xiaohaibin/XBanner#109]
pointNormal 与 pointSelect 设置为两张大型不一样图片时，第一张正常，后面的宽高就只有小的那张大小了

**Comment by xiaohaibin** [comment]
版本多少，该问题在早期版本已经修复，请更新到最新版本




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

On 06/20/2019 11:21, qitian134 wrote:

pointNormal 与 pointSelect 设置为两张大型不一样图片时，第一张正常，后面的宽高就只有小的那张大小了

**Comment by qitian134** [comment]
不好意思哈，学习别人的项目看到的，close吧，麻烦了
