### ISSUE TITLE
你的首页美誉写完全啊，

### ISSUE THREAD

**Issue by DavidWeiZhong** [xiaohaibin/XBanner#11]
先setmAdapger((),在setDate()

**Comment by xiaohaibin** [comment]
啥意思？哪里没写完全？

**Comment by DavidWeiZhong** [comment]
我已开始没有setmAdapter，导致图片一直没有加载出来，我以为没有用了，你的主界面有没有要求要写这个

**Comment by DavidWeiZhong** [comment]
我还以为你的xBanner里面有像Glide等下载图片的呢，我去看你的源码发现没有，才继续看你的项目，发现要先setmAdapter()

**Comment by DavidWeiZhong** [comment]
功能很强大，写的很好

**Comment by xiaohaibin** [comment]
我一直有在ReadMe上写的，你可能没注意到哈
![qq 20161031173849](https://cloud.githubusercontent.com/assets/11681218/19849959/ed2f0084-9f90-11e6-9845-d82d286a25d4.png)

**Comment by xiaohaibin** [comment]
谢谢，还在继续完善中，欢迎提建议

**Comment by DavidWeiZhong** [comment]
哦，我看到了，你那个可以怎么设置文字标题在图片的上面啊，我看你这里写了，可以加载文字的

**Comment by xiaohaibin** [comment]
嗯，1.2.2版本 可以显示文字的

**Comment by DavidWeiZhong** [comment]
用哪个方法mBanner.setText

**Comment by xiaohaibin** [comment]
你看下我的demo哈，里面写了的

**Comment by DavidWeiZhong** [comment]
好的，谢谢
