### ISSUE TITLE
placeholderDrawable的占位图显示模式

### ISSUE THREAD

**Issue by AnJiuZhe** [xiaohaibin/XBanner#110]
你好，希望新增占位图的ScaleType显示模式，我设置的占位图片变形了。

**Comment by xiaohaibin** [comment]
已加上属性，更新版本至1.6.9，新增属性scaleType

**Comment by AnJiuZhe** [comment]
谢谢啦

**Comment by amosxb** [comment]
不行啊，我设置了scaleType  好像没有任何反应

**Comment by xiaohaibin** [comment]
是占位图的，你确定，我测试过是可以的




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2019年06月29日 18:50，aubooo 写道：

不行啊，我设置了scaleType 好像没有任何反应

**Comment by AnRuoXi** [comment]
@xiaohaibin 发现androidX的设置无效果

**Comment by xiaohaibin** [comment]
已经修复，请更新版本





在 2019-08-28 17:13:10，"AnRuoXi" <notifications@github.com> 写道：


@xiaohaibin 发现androidX的设置无效果
