### ISSUE TITLE
图片宽度1100多px 导致ClipChildrenMode和viewpagerMargin 失效

### ISSUE THREAD

**Issue by zhupengxiang** [xiaohaibin/XBanner#112]
图片宽度1100多px 导致ClipChildrenMode和viewpagerMargin 失效

**Comment by xiaohaibin** [comment]
屏幕截图看下

**Comment by zhupengxiang** [comment]
![image](https://user-images.githubusercontent.com/17894209/60486264-3acb2300-9cd1-11e9-8939-3024c8ff3e9f.png)

![image](https://user-images.githubusercontent.com/17894209/60486327-461e4e80-9cd1-11e9-863b-f76dc3ed6fdd.png)

**Comment by zhupengxiang** [comment]
现在是在约束布局里怎么失效了

**Comment by xiaohaibin** [comment]
![image](https://user-images.githubusercontent.com/11681218/60491085-80d8b480-9cda-11e9-9eeb-511ee92eaeef.png)
数据少于两条，需要额外加个属性设置
