### ISSUE TITLE
无响应的问题，当使用了一屏多个模式，事件无响应

### ISSUE THREAD

**Issue by luoqqsh** [xiaohaibin/XBanner#114]
能不能不要拦截事件，或者给个设置开关。左右两边无法移动，也无法点击。就像这样的。
![image](https://user-images.githubusercontent.com/12087574/60652218-65a4ab00-9e7a-11e9-9f33-a19a67d4b218.png)

现在需要左右两边能滑动，也能有点击事件

**Comment by xiaohaibin** [comment]
可以，我加个属性或者方法

**Comment by xiaohaibin** [comment]
已经处理好了，版本更新到1.7.0，无需设置属性

**Comment by luoqqsh** [comment]
刚测试了，还存在两个问题
1.点击左侧区域监听到的位置和中间区域的数据是一样的，应该是不一样的数据。我打印了position，假如中间是1，实际监听到左边的还是1，左边正确的应该是0。右侧区域没有问题。
2.当我手在左侧区域和右侧区域时滑动无效，只能在中间区域进行手势滑动，能否优化下

**Comment by xiaohaibin** [comment]
啥机型，我这里是正常的呢，滑动点击正常




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2019年07月05日 14:42，luoqqsh 写道：

刚测试了，还存在两个问题
1.点击左侧区域监听到的位置和中间区域的数据是一样的，应该是不一样的数据。我打印了position，假如中间是1，实际监听到左边的还是1，左边正确的应该是0。右侧区域没有问题。
2.当我手在左侧区域和右侧区域时滑动无效，只能在中间区域进行手势滑动，能否优化下

**Comment by luoqqsh** [comment]
机型：华为P9 plus、小米6、VIVO x20A
3个手机一样的情况。系统都是8.0和9.0的
1.第一个点击事件不正确的问题在你的demo上测试了，一样存在问题，没做任何改动，看的是clipchildrenMode里的最后一个
2.左右侧区域滑动无效，试了3个机型都是一样的情况，不知道我设置的有没有错误，帮忙看下
![image](https://user-images.githubusercontent.com/12087574/60705096-ceeaf380-9f38-11e9-9c47-44c032157581.png)
![image](https://user-images.githubusercontent.com/12087574/60705120-da3e1f00-9f38-11e9-94e4-a13dffed05b6.png)
