### ISSUE TITLE
开启混淆后图片不显示

### ISSUE THREAD

**Issue by show1hand** [xiaohaibin/XBanner#115]
不混淆的话可以正常显示，不知道是什么问题

>

    private fun initBanner() {
        val headerView = View.inflate(activity, R.layout.item_home_banner, null)
        mXBanner = headerView.findViewById(R.id.banner)
        homeAdapter.addHeaderView(headerView)
        mXBanner.loadImage { _, model, view, _ ->
            //在此处使用图片加载框架加载图片，demo中使用glide加载，可替换成自己项目中的图片加载框架
            ImageLoader.loadRoundedPicture(view as ImageView, (model as BannerResult).img)
        }
        mXBanner.setOnItemClickListener { _, model, view, position ->
            val data = model as BannerResult
            actionVideoActivity(data.id, data.pic)
        }
    }

    override fun loadData(isRefresh: Boolean) {
        viewModel.loadHomeData()
        viewModel.multipleItem.observe(this, Observer {
            if (operationState == 1) {
                homeAdapter.setSpanSizeLookup { _, position -> it.list[position].spanSize }
                initBanner()
                operationState = 2
            }
            homeAdapter.setNewData(it.list)
            mXBanner.setAutoPlayAble(it.bannerBean.result.size > 1)
            mXBanner.setBannerData(it.bannerBean.result)
        })
    }

> 
混淆配置
> 
release {
            //混淆
            minifyEnabled true
            // Zipalign优化
            zipAlignEnabled true
            // 移除无用的resource文件
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            //签名
            signingConfig signingConfigs.release
        }
>

**Comment by xiaohaibin** [comment]
混淆配置加了没，混淆的时候，你打印看下，图片地址这些传过来没，图片加载你自己处理的

**Comment by show1hand** [comment]
找到原因了，是我的问题，banner的实体类忘了配置，不小心被我混淆了，导致数据错误。
