### ISSUE TITLE
当使用了一屏多个模式，无响应问题优化后存在问题

### ISSUE THREAD

**Issue by luoqqsh** [xiaohaibin/XBanner#116]
刚测试了，还存在两个问题
1.点击左侧区域监听到的位置和中间区域的数据是一样的，应该是不一样的数据。我打印了position，假如中间是1，实际监听到左边的还是1，左边正确的应该是0。右侧区域没有问题。
2.当我手在左侧区域和右侧区域时滑动无效，只能在中间区域进行手势滑动，能否优化下

**Comment by xiaohaibin** [comment]
滑动我测试了一下，没问题，左侧点击确实有点问题，我修改下

**Comment by luoqqsh** [comment]
好的，左右区域滑动不了的问题，帮忙看下有没有哪里配置错误或者漏掉什么参数的
![image](https://user-images.githubusercontent.com/12087574/60706953-2be8a880-9f3d-11e9-95a5-d406cf7faa9c.png)
![image](https://user-images.githubusercontent.com/12087574/60706960-3014c600-9f3d-11e9-89d0-01fe893294a9.png)

**Comment by luoqqsh** [comment]
左侧点击的问题什么时候能优化下，麻烦你了

**Comment by xiaohaibin** [comment]
不好意思，这两天有点忙，暂时还没找到具体原因，我继续跟踪下

**Comment by xiaohaibin** [comment]
该问题已修复，请更新至新版本
