### ISSUE TITLE
动态设置高度

### ISSUE THREAD

**Issue by zhangjianwei1** [xiaohaibin/XBanner#118]
是否支持根据加载的网络图片动态设置高度

**Comment by xiaohaibin** [comment]
可以让图片自适应高度

**Comment by zhangjianwei1** [comment]
现在Xbanner是包裹在NestedScrollView里，我尝试给Xbanner设置wrap_content，但是等图片加载出来之后发现Xbanner没有高度，无法自适应

**Comment by xiaohaibin** [comment]
Banner高度要设置，图片高度可以自适应




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2019年07月11日 10:01，zhangjianwei1 写道：

现在Xbanner是包裹在NestedScrollView里，我尝试给Xbanner设置wrap_content，但是等图片加载出来之后发现Xbanner没有高度，无法自适应

**Comment by zhangjianwei1** [comment]
banner高度已经固定的话又怎么自适应呢，已经被限制住了

**Comment by xiaohaibin** [comment]
比如商品详情里的banner图，查看大图图片显示是自适应的，如果要动态设置框架的高度，只能自己动态计算到高度之后再去设置

**Comment by zhangjianwei1** [comment]
好的，多谢了，就是想问问有没有这个，问题我关了哈，多谢
