### ISSUE TITLE
可否增加两点功能呢？

### ISSUE THREAD

**Issue by greatflag** [xiaohaibin/XBanner#12]
@xiaohaibin 您好，作为广告轮播控件比较完美了。但能否再增加两个功能：
1. 指示器支持1/5、3/5这种页数的提示方式
2. 增加页面切换listener？

**Comment by xiaohaibin** [comment]
这个可以增加，近期更新

**Comment by xiaohaibin** [comment]
第一个功能已经实现了，详情请查看ReadMe
