### ISSUE TITLE
能加一个效果么？

### ISSUE THREAD

**Issue by hzyshare** [xiaohaibin/XBanner#120]
http://sc.chinaz.com/jiaobendemo.aspx?downloadid=6201990216498  应该设置下translationx就可以，看了一圈，发现你这控件挺不错，就直接拿来用了，但是需要这个效果。。虽然说了可以添加自定义，不过不知道怎么添加

**Comment by xiaohaibin** [comment]
添加方式跟viewpager添加动画是一致的，本身是基于viewpager开发的控件

**Comment by xiaohaibin** [comment]
该效果已添加，更新新版版本可以使用，更多效果可以自己自定义动画实现
