### ISSUE TITLE
往前滑动崩溃

### ISSUE THREAD

**Issue by WeiLanXingchen** [xiaohaibin/XBanner#125]
手势一直不停往前滑动APP挂了

**Comment by xiaohaibin** [comment]
麻烦贴一下报错日志呢




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2019年08月27日 17:59，WeiLanXingchen 写道：

手势一直不停往前滑动APP挂了

**Comment by WeiLanXingchen** [comment]
ClipChildrenMode里不断滑动时程序崩溃了

E/linker: readlink('/proc/self/fd/22') failed: Permission denied [fd=22]
08-27 23:38:19.652 8012-8024/? E/linker: warning: unable to get realpath for the library "/system/lib64/hw/gralloc.hi6250.so". Will use given name.
08-27 23:38:19.821 1034-1302/? E/InputDispatcher: channel '935dd13 com.stx.xhb.xbanner/com.stx.xhb.demo.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
08-27 23:38:20.029 1034-1827/? E/libprocessgroup: failed to kill 1 processes for processgroup 7475
08-27 23:38:20.089 8025-8050/? E/linker: readlink('/proc/self/fd/22') failed: Permission denied [fd=22]
08-27 23:38:20.089 8025-8050/? E/linker: warning: unable to get realpath for the library "/system/lib64/hw/gralloc.hi6250.so". Will use given name.
08-27 23:38:20.183 8012-8024/? E/linker: readlink('/proc/self/fd/23') failed: Permission denied [fd=23]
08-27 23:38:20.183 8012-8024/? E/linker: warning: unable to get realpath for the library "libion.so". Will use given name.
08-27 23:38:20.184 8025-8050/? E/linker: readlink('/proc/self/fd/24') failed: Permission denied [fd=24]
08-27 23:38:20.184 8025-8050/? E/linker: warning: unable to get realpath for the library "libion.so". Will use given name.
08-27 23:38:20.791 1034-1355/? E/HwCHRWebMonitor: running processNamecom.stx.xhb.xbanner
08-27 23:38:20.792 1034-1355/? E/HwCHRWebMonitor: HwCHRWifiUIDWebSpeed [appName=com.stx.xhb.xbanner UID=11190  WEBSENDSEGS=734  WEBRESENDSEGS=0  WEBRECVSEGS=1634  WEBERRSEGS=0  WEBOUTRSTS=0  WEBESTABLISRST=0  WEBRTTDURATION=15  WEBRTTSEGS=12  WEBSNDDUPACKS=0  suckTimes=0 recovage_times=1]
08-27 23:38:20.793 8012-8012/? E/mutiCardFactory: [main-1]FeatureOption.MTK_GEMINI_SUPPORTjava.lang.ClassNotFoundException: com.mediatek.common.featureoption.FeatureOption(android/null:-1)
08-27 23:38:20.798 1034-1355/? E/HwWifiSpeedBaseCheck: recv_packet=0 send_packet=1 recv_packet/send_packet=0.0
08-27 23:38:20.799 1034-1355/? E/HwCHRWebMonitor: HwCHRWifiUIDWebSpeed [appName=com.sohu.inputmethod.sogou UID=10110  WEBSENDSEGS=1  WEBRESENDSEGS=1  WEBRECVSEGS=0  WEBERRSEGS=0  WEBOUTRSTS=0  WEBESTABLISRST=0  WEBRTTDURATION=0  WEBRTTSEGS=0  WEBSNDDUPACKS=0  suckTimes=1 recovage_times=0]
08-27 23:38:20.799 1034-1355/? E/HwCHRWebMonitor: WebMonitor [mNetWorkIsSuck=false mUIDIsSuck=]  WebSpeed [WEBSENDSEGS=750  WEBRESENDSEGS=1  WEBRECVSEGS=1641  WEBERRSEGS=0  WEBOUTRSTS=0  WEBESTABLISRST=0  WEBRTTDURATION=29  WEBRTTSEGS=19  WEBSRTT=120  WEBSNDDUPACKS=0  SENDSEGS=0  RESENDSEGS=0  RECVSEGS=0  ERRSEGS=0  OUTRSTS=0  ESTABLISRST=0  RTTDURATION=0  RTTSEGS=0  SNDDUPACKS=0  suckTimes=0 recovage_times=1]
08-27 23:38:20.890 8037-8080/com.stx.xhb.xbanner E/Xbanner: ========request'log=======
08-27 23:38:20.890 8037-8080/com.stx.xhb.xbanner E/Xbanner: method : GET
08-27 23:38:20.890 8037-8080/com.stx.xhb.xbanner E/Xbanner: url : https://api.tuchong.com/2/wall-paper/app
08-27 23:38:20.890 8037-8080/com.stx.xhb.xbanner E/Xbanner: ========request'log=======end
08-27 23:38:20.902 8025-8072/? E/ActivityThread: Failed to find provider info for com.huawei.android.hicloud.loginProvider
08-27 23:38:20.902 8025-8072/? E/ContactsProtector: getHiCloudAccountData query fail
08-27 23:38:21.050 471-471/? E/Thermal-daemon: [pa_0] temp_new :37  temp_old :36
08-27 23:38:21.050 471-471/? E/Thermal-daemon: Report temperature: [pa_0] temp :37  report_threshold:1
08-27 23:38:21.051 471-471/? E/Thermal-daemon: [ap] temp_new :38  temp_old :37
08-27 23:38:21.051 471-471/? E/Thermal-daemon: Report temperature: [ap] temp :38  report_threshold:1
08-27 23:38:21.166 1034-1316/? E/WifiConfigStore: updateConfiguration freq=2417 BSSID=ec:38:8f:ae:4c:f4 RSSI=-51 "ChinaNet-mDS5"WPA_PSK
08-27 23:38:22.047 8037-8080/com.stx.xhb.xbanner E/Xbanner: ========response'log=======
08-27 23:38:22.047 8037-8080/com.stx.xhb.xbanner E/Xbanner: url : https://api.tuchong.com/2/wall-paper/app
08-27 23:38:22.048 8037-8080/com.stx.xhb.xbanner E/Xbanner: code : 200
08-27 23:38:22.048 8037-8080/com.stx.xhb.xbanner E/Xbanner: protocol : h2
08-27 23:38:22.048 8037-8080/com.stx.xhb.xbanner E/Xbanner: ========response'log=======end

**Comment by xiaohaibin** [comment]
新版本修复
