### ISSUE TITLE
问个问题，滑动监听怎么设置

### ISSUE THREAD

**Issue by zhangjianwei1** [xiaohaibin/XBanner#129]
现在有个需求，需要根据banner滑动到哪张设置个东西，请问下这个滑动监听怎么设置

**Comment by xiaohaibin** [comment]
mXBanner.setOnPageChangeListener(new ViewPager.SimpleOnPageChangeListener() {
            @Override
            public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {
             
            }
        });

**Comment by zhangjianwei1** [comment]
多谢

**Comment by zhangjianwei1** [comment]
pictureBanner.setOnPageChangeListener(new ViewPager.SimpleOnPageChangeListener() {
            @Override
            public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {
//                if (positionOffset == SCROLL_STATE_IDLE) {
                    //滚动结束
                    ToastUtils.show(mContext, position + "");
//                }
            }
        });
我这么设置的，然后banner是多显循环模式，循环到第二次的时候position对应的值不对

**Comment by zhangjianwei1** [comment]
onPageSelected用这个好了。。。
