### ISSUE TITLE
banner无法自动滑动mBanner.setAllowUserScrollable(false);

### ISSUE THREAD

**Issue by 01wneo** [xiaohaibin/XBanner#136]
设置属性mBanner.setAllowUserScrollable(false);之后，手动滑动banner，banner就会停止，不再自动轮播

**Comment by xiaohaibin** [comment]
该属性是设置不允许用户手动滚动图片

**Comment by SkyUnicorn** [comment]
我也遇到这个问题了，需求是设置不让用户滑动，在实际情况下，用户不滑动是正常自动播放，而执行手动滑动这个动作后，虽然不会操作banner的滚动，但是会导致banner自动播放停止

**Comment by xiaohaibin** [comment]
mBanner.setAllowUserScrollable(false);测试过，未复现问题，设置该属性之后，尝试滑动图片依然会自动滚动

**Comment by xiaohaibin** [comment]
mBanner.setAllowUserScrollable(false);
测试过，未复现问题，设置该属性之后，尝试滑动图片依然会自动滚动




在 2019-12-16 16:43:53，"SkyUnicorn" <notifications@github.com> 写道：


我也遇到这个问题了，需求是设置不让用户滑动，在实际情况下，用户不滑动是正常自动播放，而执行手动滑动这个动作后，虽然不会操作banner的滚动，但是会导致banner自动播放停止
