### ISSUE TITLE
只有一张图时不显示指示点

### ISSUE THREAD

**Issue by ohyesly** [xiaohaibin/XBanner#14]
如题，当只有一张图时不显示知识点，望修复，谢谢

**Comment by xiaohaibin** [comment]
这个不是bug哈，我代码中是这么设置的 ，只有一张图片时不显示状态点，如果需要一个设置方法，我后面添加，你比较急的话，可以把源码down下来，自己简单改一下就好

**Comment by xiaohaibin** [comment]
最新版本已经可以自己设置当只有一张图片时是否显示指示点，详情请查看ReadMe
