### ISSUE TITLE
pointsPosition为LEFT，isShowTips为false时会空指针

### ISSUE THREAD

**Issue by zhaoshuiruoli** [xiaohaibin/XBanner#141]
Version 1.7.0
代码中LEFT == mPointPosition的条件下，未判断isShowTips直接使用mTipTv.setGravity，会导致空指针异常，望修复，XBanner类相关代码如下

/*设置指示器布局位置*/
        if (CENTER == mPointPosition) {
            mPointRealContainerLp.addRule(RelativeLayout.CENTER_HORIZONTAL);
            pointLp.addRule(RelativeLayout.LEFT_OF, R.id.xbanner_pointId);
        } else if (LEFT == mPointPosition) {
            mPointRealContainerLp.addRule(RelativeLayout.ALIGN_PARENT_LEFT);
            mTipTv.setGravity(Gravity.CENTER_VERTICAL | Gravity.RIGHT);
            pointLp.addRule(RelativeLayout.RIGHT_OF, R.id.xbanner_pointId);
        } else if (RIGHT == mPointPosition) {
            mPointRealContainerLp.addRule(RelativeLayout.ALIGN_PARENT_RIGHT);
            pointLp.addRule(RelativeLayout.LEFT_OF, R.id.xbanner_pointId);
        }

**Comment by xiaohaibin** [comment]
已修复
