### ISSUE TITLE
设置图片属性为centerCrop后 圆角会消失

### ISSUE THREAD

**Issue by 643063150** [xiaohaibin/XBanner#148]
不设置圆角正常 但是宽会根据设定的高变化，导致轮播的图宽度不一致，不知道是什么情况

**Comment by xiaohaibin** [comment]
图片加载是你自己选择的图片加载框架，圆角也是自己单独设置，框架本身不支持




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2019年12月04日 17:54，643063150 写道：

不设置圆角正常 但是宽会根据设定的高变化，导致轮播的图宽度不一致，不知道是什么情况

**Comment by 643063150** [comment]
这个问题我再外层加了一层cardview解决了，我想请教一下一屏显示多个模式页面第三个 图片在切换时会有一个形变的动画有办法关掉吗

**Comment by xiaohaibin** [comment]
可以设置成你自己的切换动画，比如你早图片都一样，你设置成默认动画效果就行，demo有事例




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2019年12月04日 19:29，643063150 写道：

这个问题我再外层加了一层cardview解决了，我想请教一下一屏显示多个模式页面第三个 图片在切换时会有一个形变的动画有办法关掉吗
