### ISSUE TITLE
集成闪退

### ISSUE THREAD

**Issue by jahenryhan** [xiaohaibin/XBanner#149]
java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 3, found: 4 Pager id: ffffffff Pager class: class com.stx.xhb.xbanner.XBannerViewPager Problematic adapter: class com.stx.xhb.xbanner.XBanner$XBannerPageAdapter

**Comment by xiaohaibin** [comment]
什么版本？刚提交了一个修复版本，请下载源码测试，是否复现，谢谢
