### ISSUE TITLE
重新setData的时候报NullPointerException

### ISSUE THREAD

**Issue by isiyin** [xiaohaibin/XBanner#15]
项目中有个地方需要对Banner数据进行刷新，所以重新setData，之后报了NullPointerException
看了一下XBanner.java的源码，发现这个地方似乎写得有点问题，这里判断mViewPager是否不为空，如果不为空的的话会置null，那么接下来初始化mViewPager调用setAdapter就肯定会引发NullPointerException。（版本1.2.3）

       if (mViewPager != null && this.equals(mViewPager.getParent())) {
            this.removeView(mViewPager);
            mViewPager = null;
        }
        //初始化ViewPager
        mViewPager.setAdapter(new XBannerPageAdapter());

**Comment by xiaohaibin** [comment]
好的，我看下

**Comment by xiaohaibin** [comment]
已经修复，在新版本1.2.4，可以试下，有问题提issue
