### ISSUE TITLE
一屏显示多张图的时候，初次选中第二张图时候，第三张图消息初始化有问题

### ISSUE THREAD

**Issue by dazhi3219** [xiaohaibin/XBanner#153]
一屏显示多张图的时候，初次选中第二张图时候，第三张图消息初始化有问题，当再次稍微滑动过后，就正常显示了
![1111](https://user-images.githubusercontent.com/19549398/72202506-475bdf80-349b-11ea-903e-9dbde963fd00.png)

**Comment by xiaohaibin** [comment]
获取viewpager然后设置offolimit为你的图片数




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2020年01月11日 17:53，dazhi3219 写道：

一屏显示多张图的时候，初次选中第二张图时候，第三张图消息初始化有问题，当再次稍微滑动过后，就正常显示了
