### ISSUE TITLE
RecyclerView中使用的细节问题

### ISSUE THREAD

**Issue by mayangyang-github** [xiaohaibin/XBanner#154]
在RecyclerView 中使用 XBanner 作为头布局的话, 当这个头布局由 不可见 变为 可见 的时候, 第一下的动画就没有了, 我试过很多由VewPager打造的banner, 基本都存在这个问题... 
哎, 怎么解决啊

**Comment by xiaohaibin** [comment]
目前这个这个问题是为了解决滑动不可见变为可见的卡顿问题，所以第一次会把动画过了，直接无缝跳下一张
