### ISSUE TITLE
setBannerData方法的models参数的泛型

### ISSUE THREAD

**Issue by Sumsear** [xiaohaibin/XBanner#157]
在com.github.xiaohaibin:XBanner:androidx_v1.0.6版本中setBannerData(@LayoutRes int layoutResId, @NonNull List<? extends SimpleBannerInfo> models)方法传入的这个list已经规定了这个list是一个继承SimpleBannerInfo的对象的容器，这个泛型为什么不直接用BaseBannerInfo这个接口呢？如果是BaseBannerInfo应该更加友好！

**Comment by xiaohaibin** [comment]
已修复，感谢指正
