### ISSUE TITLE
androidX分支报错

### ISSUE THREAD

**Issue by dapanjimianpaigumian** [xiaohaibin/XBanner#158]
XBanner类825行报错。
提示：You must not call setTag() on a view Glide is targeting
去掉825行代码后程序正常运行。
不知道有没有什么其他的隐藏问题。。

**Comment by xiaohaibin** [comment]
这是glide配置一下就好了




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2020年03月21日 17:09，大盘鸡面排骨面 写道：

XBanner类825行报错。
提示：You must not call setTag() on a view Glide is targeting
去掉825行代码后程序正常运行。
不知道有没有什么其他的隐藏问题。。

**Comment by KrishuCN** [comment]
> 这是glide配置一下就好了 | | 萧海斌 邮箱：xhb_199409@163.com | 签名由 网易邮箱大师 定制 在2020年03月21日 17:09，大盘鸡面排骨面 写道： XBanner类825行报错。 提示：You must not call setTag() on a view Glide is targeting 去掉825行代码后程序正常运行。 不知道有没有什么其他的隐藏问题。。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我也遇到同样的问题。请问如何配置Glide避免冲突

**Comment by xiaohaibin** [comment]
Application 添加如下：
ViewTarget.setTagId(R.id.glide_tag);

**Comment by KrishuCN** [comment]
> Application 添加如下：
> ViewTarget.setTagId(R.id.glide_tag);

解决了，感谢
