### ISSUE TITLE
设置点击事件后自动翻页

### ISSUE THREAD

**Issue by wp549741214** [xiaohaibin/XBanner#159]
version：:XBanner:androidx_v1.0.6
question ： 设置点击事件后，点击图片，banner自动切第二页，然后才跳转。最后一页点击后，切换空白页面，才跳转。
左右滑动一遍之后就没有问题

  XBanner banner = helper.getView(R.id.ivDetailImg);
                    banner.setBannerData(R.layout.item_detail_banner, imgUrls);
                    banner.loadImage(new XBanner.XBannerAdapter() {
                        @Override
                        public void loadBanner(XBanner banner, Object model, View view, int position) {
                            view.setTag(null);
                            ImageView iv = view.findViewById(R.id.ivBannerImg);
                            Glide.with(mContext).load(((SimpleBannerInfo)
                                    model).getXBannerUrl()).apply(new RequestOptions().centerInside()).into(iv);
                        }
                    });
                    banner.setOnItemClickListener(new XBanner.OnItemClickListener() {
                        @Override
                        public void onItemClick(XBanner banner, Object model, View view, int position) {
                            LogUtils.e("pengpeng",position+"----");
                            Intent previewInt = new Intent(mContext, GalleryActivity.class);
                            previewInt.putExtra(Constants.PICTURE_PREVIEW_POSITION, position);
                            previewInt.putStringArrayListExtra(Constants.PICTURE_PREVIEW_DATA, (ArrayList<String>) header.getPictures());
                            mContext.startActivity(previewInt);
                        }
                    });
                    banner.setCustomPageTransformer(new DepthPageTransformer());

**Comment by StuStatic** [comment]
点击的时候autoplay = false试试

**Comment by xiaohaibin** [comment]
这个之前框架一屏多显模式有设置点击两侧图片切换的逻辑，可更新新版本再试试
