### ISSUE TITLE
当图片只有两张时，显示空白页

### ISSUE THREAD

**Issue by chinachen01** [xiaohaibin/XBanner#16]
作者采用的viewpager轮播方式在图片为2张时会有bug，而代码并没有对此做特殊处理。
常用的做法是将图片翻倍，指示器仍然为2个。
以下链接是相关资料供参考：
[http://blog.csdn.net/kpioneer123/article/details/51121550](url)

**Comment by chinachen01** [comment]
更新一下，我用的图片加载库是Fresco，我自己尝试修复了下这个bug，我在XBanner中增加了一个变量mIsTwoImg,然后当数据源size为2时将数据源size设为4，在addPoints()方法中points的数量仍然为2，最后在onPageSelected(),instantiateItem()方法中再重新计算realPostion

**Comment by xiaohaibin** [comment]
好的，我找下原因，近期修复

**Comment by xiaohaibin** [comment]
两张图片空白的bug已经修复，更新到1.2.5即可
