### ISSUE TITLE
添加到RecyclerView的头部之后不会自动播放

### ISSUE THREAD

**Issue by DARTTTTT** [xiaohaibin/XBanner#160]

**Comment by xiaohaibin** [comment]
设置数据之后，也需要在代码设置自动轮播




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2020年04月05日 21:08，switch 写道：

**Comment by DARTTTTT** [comment]
> 设置数据之后，也需要在代码设置自动轮播
> 
> 
> 
> 
> | |
> 萧海斌
> 邮箱：xhb_199409@163.com
> |
> 
> 签名由 网易邮箱大师 定制
> 
> 在2020年04月05日 21:08，switch 写道：
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

设置了 也没有用

**Comment by xiaohaibin** [comment]
贴下代码看下

**Comment by DARTTTTT** [comment]
> 贴下代码看下

我换了下布局了 避免了放头部不自动轮播的问题

**Comment by xiaohaibin** [comment]
好的👌🏻




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2020年04月12日 23:51，switch 写道：

贴下代码看下

我换了下布局了 避免了放头部不自动轮播的问题
