### ISSUE TITLE
你好，有那个方法效果是类似于viewpager的 setCurrentItem(0);

### ISSUE THREAD

**Issue by binbinyYang** [xiaohaibin/XBanner#161]
你好，有那个方法效果是类似于viewpager的 setCurrentItem(0);

**Comment by xiaohaibin** [comment]
有的，setBannerItem()具体可以看下demo




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2020年04月13日 14:52，杨彬 写道：

你好，有那个方法效果是类似于viewpager的 setCurrentItem(0);

**Comment by binbinyYang** [comment]
你回复的真快，刚我点进去看了源码 确实是这个 谢谢 已经解决问题了

**Comment by xiaohaibin** [comment]
😃




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2020年04月13日 14:55，杨彬 写道：

你回复的真快，刚我点进去看了源码 确实是这个 谢谢 已经解决问题了
