### ISSUE TITLE
请问想要实现展示完整的第一个,和只有一半的第二个该怎么做呢?我看这个库好像没有这样的效果

### ISSUE THREAD

**Issue by roybill** [xiaohaibin/XBanner#164]
如果没有的话,作者可否加上这个功能呢?谢谢

**Comment by xiaohaibin** [comment]
这块自定义动画就可以了




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2020年04月28日 16:25，roybill 写道：

如果没有的话,作者可否加上这个功能呢?谢谢
