### ISSUE TITLE
isClipChildrenMode="true"当图片为两张或者一张时图片设置左右margin没用

### ISSUE THREAD

**Issue by yangmengli** [xiaohaibin/XBanner#165]
RT

**Comment by yangmengli** [comment]
设置app:clipChildrenLeftRightMargin="130dp"失效，图片会横向撑满窗口

**Comment by zeR0Lu** [comment]
@yangmengli 我也遇到了同样的问题了，不知道神马时候可以修复

**Comment by xiaohaibin** [comment]
isClipChildrenModeLessThree	少于三张是否支持一屏多显模式	boolean类型，默认为false 默认不开启

**Comment by xiaohaibin** [comment]
注意看文档

**Comment by yangmengli** [comment]
@xiaohaibin 我看到了，不过如果有两张能否只显示右边有一张，两边都有有点怪。。。
