### ISSUE TITLE
如何禁止左右切换（自动手动都不可切换）、恢复左右切换

### ISSUE THREAD

**Issue by LiuDongCai** [xiaohaibin/XBanner#166]
如何禁止左右切换（自动手动都不可切换）、恢复左右切换

**Comment by xiaohaibin** [comment]
一屏多显模式下的左右切换么

**Comment by LiuDongCai** [comment]
是的

**Comment by xiaohaibin** [comment]
有个属性设置，代码已经传上去了，文档还没更新




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2020年05月09日 09:41，LiuDongCai 写道：

是的

**Comment by LiuDongCai** [comment]
另外想问下，banner数据只有2个，怎么设置一屏多显
setIsClipChildrenMode(true)这个没用

**Comment by xiaohaibin** [comment]
有个lessthree的属性，你看下文档，有说明




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2020年05月09日 09:46，LiuDongCai 写道：

另外想问下，banner数据只有2个，怎么设置一屏多显
setIsClipChildrenMode(true)这个没用

**Comment by LiuDongCai** [comment]
> 有个属性设置，代码已经传上去了，文档还没更新 | | 萧海斌 邮箱：xhb_199409@163.com | 签名由 网易邮箱大师 定制 在2020年05月09日 09:41，LiuDongCai 写道： 是的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

这个属性是什么呢？
com.github.xiaohaibin:XBanner:androidx_v1.0.8这个版本有吗
