### ISSUE TITLE
自定义布局CardView不显示圆角

### ISSUE THREAD

**Issue by mofei666** [xiaohaibin/XBanner#169]
<androidx.cardview.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:cardCornerRadius="24dp"
    app:cardElevation="3dp" />
自定义布局是这样的，但是不显示圆角

**Comment by xiaohaibin** [comment]
完整布局看下呢

**Comment by Alvin9234** [comment]
不显示圆角，设置一下margin就显示了
