### ISSUE TITLE
在网络很慢的情况下，会报空指针

### ISSUE THREAD

**Issue by chinachen01** [xiaohaibin/XBanner#17]
private static class AutoSwitchTask implements Runnable {
        private final WeakReference<XBanner> mXBanner;
 
        private AutoSwitchTask(XBanner mXBanner) {
            this.mXBanner = new WeakReference<>(mXBanner);
        }
 
        @Override
        public void run() {
            XBanner banner = mXBanner.get();
            if (banner != null) {
                int currentItem = banner.mViewPager.getCurrentItem() + 1;
                banner.mViewPager.setCurrentItem(currentItem);
                banner.postDelayed(banner.mAutoSwitchTask, banner.mAutoPalyTime);
            }
        }
    }
其中banner.mViewPager.getCurrentItem()会报空指针异常，看了下原因,initViewPager()是在setData方法中调用的，如果网络状况很糟糕，在run方法执行时还没调用setData就会发生此异常。

**Comment by xiaohaibin** [comment]
已经修复了，感谢提醒，在1.2.6版本上，可以更新下。没问题的话，麻烦closed一下，谢谢。
