### ISSUE TITLE
setBannerData()方法怎么加标题？

### ISSUE THREAD

**Issue by mofei666** [xiaohaibin/XBanner#171]
setBannerData()方法怎么加标题？
好像只有setData()可以加标题，但是setData()过期了

**Comment by xiaohaibin** [comment]
看下demo哈，有例子

**Comment by mofei666** [comment]
> 看下demo哈，有例子

                        //刷新数据之后，需要重新设置是否支持自动轮播
                        mBanner.setAutoPlayAble(data.size() > 1);
                        mBanner.setIsClipChildrenMode(true);
                        //老方法，不推荐使用
                        mBanner.setData(R.layout.layout_fresco_imageview, data,null);

                        //刷新数据之后，需要重新设置是否支持自动轮播
                        mBanner2.setAutoPlayAble(data.size() > 1);
                        mBanner2.setIsClipChildrenMode(true);
                        mBanner2.setBannerData(R.layout.layout_fresco_imageview, data);
我看demo是这样的，然后setData()设置的null，我自己给加了tips，但是没用，而且我现在运行XBanner就没有图片，不知道为什么，之前可以的，现在不能联网了？但是在浏览器上复制链接是可以看到json的，本地的也可以，然后就是demo上没找到用setBannerData（）设置标题的代码，点进源码里，setBannerData（）方法里没有tips参数，只有setData（）里有。。。

**Comment by xiaohaibin** [comment]
这个方法把数据放在实体类了，看下这个类，你就明白了 TuchongEntity
