### ISSUE TITLE
一屏多模式状态下，后台返回的图片需要拼接，直接中间图片把屏幕宽占满了，我直接从网上扒下来的数据可以一屏多模式，是什么问题呢？

### ISSUE THREAD

**Issue by wangsong1991** [xiaohaibin/XBanner#173]
![微信图片_20200617211355](https://user-images.githubusercontent.com/9698820/84902643-a7585100-b0df-11ea-984d-49271b71ba7e.jpg)

**Comment by xiaohaibin** [comment]
图片数量少于三张会默认铺满屏幕，文档有个属性，设置一下就可以了
