### ISSUE TITLE
设置一屏显示多个视图，在数据发生变化时，可能会出现设置失败的bug

### ISSUE THREAD

**Issue by zhaoshuiruoli** [xiaohaibin/XBanner#174]
在XBanner类的setBannerData和setData方法中，有下面两段代码
if (!mIsClipChildrenModeLessThree && views.size() < 3) {
            mIsClipChildrenMode = false;
 }
if (mViews.isEmpty()) {
            mIsAutoPlay = false;
            mIsClipChildrenMode = false;
 }
如果数据一开始为空或小于3条，mIsClipChildrenMode会设置为false，在数据刷新后，不会重新置为true，造成isClipChildrenMode设置失效，这个可以修复下

**Comment by xiaohaibin** [comment]
了解，感谢反馈，目前可以在setdata方法之后代码再次设置IsClipChildrenMode属性
