### ISSUE TITLE
1.7.3 加载图片时 错误

### ISSUE THREAD

**Issue by zhangshubin01** [xiaohaibin/XBanner#177]
You must not call setTag() on a view Glide is targeting

**Comment by zhangshubin01** [comment]
banner.loadImage(new XBanner.XBannerAdapter() {
            @Override
            public void loadBanner(XBanner banner, Object model, View view, int position) {
            Glide 加载图片 报错
}

**Comment by xiaohaibin** [comment]
该问题已经在1.7.4修复，请更新
