### ISSUE TITLE
一屏多个点击事件

### ISSUE THREAD

**Issue by AttackPangHu** [xiaohaibin/XBanner#178]
一屏多个模式，禁止轮播后，我点击后面一条，能滑动后面一条展示。但是我点击前面一条，不会滑到签一条去

**Comment by AttackPangHu** [comment]
版本'com.github.xiaohaibin:XBanner:androidx_v1.0.8'

**Comment by xiaohaibin** [comment]
感谢反馈，已修复该问题

**Comment by AttackPangHu** [comment]
升級到com.github.xiaohaibin:XBanner:androidx_v1.0.9' 包名变了，但是这个问题好像还是存在

**Comment by xiaohaibin** [comment]
不好意思哈，麻烦再更新下，1.1.0 哈，版本更新分支错了

**Comment by AttackPangHu** [comment]
好的，作者大大辛苦了。
