### ISSUE TITLE
isClipChildrenMode属性设置无效

### ISSUE THREAD

**Issue by m-tso** [xiaohaibin/XBanner#179]
当所使用的banner布局在recyclerview中使用时，该属性设置似乎无效，代码如下：
<LinearLayout xmlns:app="http://schemas.android.com/apk/res-auto"
        android:id="@+id/rl_banner"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical">
<com.stx.xhb.xbanner.XBanner
            xmlns:app="http://schemas.android.com/apk/res-auto"
            android:id="@+id/xbanner"
            android:layout_width="match_parent"
            android:layout_height="150dp"
            app:AutoPlayTime="3000"
            app:clipChildrenLeftRightMargin="85dp"
            app:pageChangeDuration="800"
            app:pointSelect="@drawable/wan_banner_select"
            app:pointNormal="@drawable/wan_banner_unselect"
            app:isClipChildrenMode="true"/>
...........
在adapter中加载方式如下：
 view = LayoutInflater.from(parent.context)
                .inflate(R.layout.item_wan_banner,parent,false)
  val binding = DataBindingUtil.bind<WanBannerBinding>(view)!!
  holder = BaseViewHolder(binding)
这是什么问题，是我忽略了什么吗

**Comment by xiaohaibin** [comment]
代码中也要设置一下，加载数据的时候如果少于三张会重置该属性

**Comment by m-tso** [comment]
谢谢大佬！
