### ISSUE TITLE
图片铺满了，但是是设置了间距，而且在之前的项目里是好的，新建了一个项目重新用就坏了。。。

### ISSUE THREAD

**Issue by mofei666** [xiaohaibin/XBanner#180]
[效果](https://s1.ax1x.com/2020/08/08/aoCScF.png)
`//xml
            <androidx.core.widget.NestedScrollView
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginTop="8dp"
                android:scrollbars="none">

                <androidx.constraintlayout.widget.ConstraintLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content">

                    <LinearLayout
                        android:id="@+id/linearLayout"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        app:layout_constraintBottom_toBottomOf="parent"
                        app:layout_constraintEnd_toEndOf="parent"
                        app:layout_constraintStart_toStartOf="parent"
                        app:layout_constraintTop_toTopOf="parent"
                        app:layout_constraintVertical_bias="0.0">

                        <com.stx.xhb.xbanner.XBanner
                            android:id="@+id/banner"
                            android:layout_width="match_parent"
                            android:layout_height="200dp"
                            android:scaleType="centerCrop"
                            app:AutoPlayTime="3000"
                            app:clipChildrenLeftRightMargin="10dp"
                            app:isAutoPlay="true"
                            app:isClipChildrenMode="true"
                            app:isHandLoop="true"
                            app:isShowIndicatorOnlyOne="true"
                            app:isShowNumberIndicator="false"
                            app:isShowTips="false"
                            app:pageChangeDuration="1500"
                            app:placeholderDrawable="@drawable/default_image"
                            app:pointContainerPosition="BOTTOM"
                            app:pointsContainerBackground="@drawable/shape_round_8dp"
                            app:pointsPosition="RIGHT"
                            app:pointsVisibility="true"
                            app:viewPagerClipChildren="true"
                            app:viewpagerMargin="20dp" />
                    </LinearLayout>
                </androidx.constraintlayout.widget.ConstraintLayout>

            </androidx.core.widget.NestedScrollView>

    /**java
     * 初始化XBanner
     */
    private void initBanner() {
        //加载广告图片
        dataBinding.banner.loadImage((banner, model, view, position) -> {
//            SimpleDraweeView draweeView = (SimpleDraweeView) view;
//            BannerBean bannerBean = (BannerBean) model;
//            String url = bannerBean.getXBannerUrl();
//            draweeView.setImageURI(Uri.parse(url));
            //在此处使用图片加载框架加载图片，demo中使用glide加载，可替换成自己项目中的图片加载框架
            BannerBean bannerBean = (BannerBean) model;
            String url = bannerBean.getXBannerUrl();
            RoundedCorners roundedCorners = new RoundedCorners(30);
            RequestOptions options = RequestOptions.bitmapTransform(roundedCorners);
            Glide.with(WenFragment.this).load(url).placeholder(R.drawable.default_image).error(R.drawable.default_image).into((ImageView) view);
        });
        dataBinding.banner.setBannerData(data);
    }`

**Comment by xiaohaibin** [comment]
isClipChildrenModeLessThree | 少于三张是否支持一屏多显模式 | boolean类型，默认为false 默认不开启

**Comment by mofei666** [comment]
> isClipChildrenModeLessThree | 少于三张是否支持一屏多显模式 | boolean类型，默认为false 默认不开启

`
//设置了3张图片
    /**
     * 初始化XBanner
     */
    private void initBanner() {
        //加载广告图片
        dataBinding.banner.loadImage((banner, model, view, position) -> {
            SimpleDraweeView draweeView = (SimpleDraweeView) view;
            BannerBean bannerBean = (BannerBean) model;
            String url = bannerBean.getXBannerUrl();
            draweeView.setImageURI(Uri.parse(url));
            //在此处使用图片加载框架加载图片，demo中使用glide加载，可替换成自己项目中的图片加载框架
//            BannerBean bannerBean = (BannerBean) model;
//            String url = bannerBean.getXBannerUrl();
//            RoundedCorners roundedCorners = new RoundedCorners(30);
//            RequestOptions options = RequestOptions.bitmapTransform(roundedCorners);
//            Glide.with(WenFragment.this).load(url).placeholder(R.drawable.default_image).error(R.drawable.default_image).into((ImageView) view);
        });
        dataBinding.banner.setBannerData(data);
    }
    private void clearData(){
        data.clear();
        list.clear();
    }
    private void getData() {//https://s1.ax1x.com/2020/08/08/aIIyUs.png
        data.add(new BannerBean("https://s1.ax1x.com/2020/08/08/aIIyUs.png"));
        data.add(new BannerBean("https://s1.ax1x.com/2020/07/06/UPVi4A.jpg"));
        data.add(new BannerBean("https://s1.ax1x.com/2020/07/06/UPVA3t.jpg"));

        //刷新数据之后，需要重新设置是否支持自动轮播
        dataBinding.banner.setAutoPlayAble(data.size() > 1);
        dataBinding.banner.setBannerData(R.layout.layout_fresco_imageview, data);
}
`

**Comment by xiaohaibin** [comment]
截屏看下你的效果

**Comment by mofei666** [comment]
> 截屏看下你的效果
效果发了的，在标题下面的回复那里有个效果超链接，有灰色的point是正常的，但是图片超出了阴影知识框

**Comment by mofei666** [comment]
找到答案了，原来是在initBanner()里面多加了
dataBinding.banner.setBannerData(data);
去掉就好了。
