### ISSUE TITLE
找不到包

### ISSUE THREAD

**Issue by xnng** [xiaohaibin/XBanner#181]
androidx 导入依赖后xml提示找不到包
![image](https://user-images.githubusercontent.com/38936252/93082635-dae94e00-f6c3-11ea-8819-3ba55862599a.png)
导入普通依赖没问题，但是不显示轮播图

**Comment by xiaohaibin** [comment]
Androidx包路径是这个 com.stx.xhb.androidx.XBanner，多看下demo哈

**Comment by xnng** [comment]
好的，非常感谢大佬
