### ISSUE TITLE
使用自动轮播的问题

### ISSUE THREAD

**Issue by AttackPangHu** [xiaohaibin/XBanner#183]
在recycleView的adapter里使用getOtemType添加XBanner为其中一个type时，会一直触发adapter的刷新方法，导致无法显示。
当AutoPlay为false时，正常

版本号：2.1.0

**Comment by xiaohaibin** [comment]
没有2.1.0版本的

**Comment by AttackPangHu** [comment]
> 没有2.1.0版本的

看错库了，版本是     api 'com.github.xiaohaibin:XBanner:androidx_v1.1.0'

**Comment by xiaohaibin** [comment]
麻烦你核查一下代码呢，应该是代码使用的问题，框架demo中新增了recyclerview的调用方式，可以参考使用
