### ISSUE TITLE
使用AndroidX  compileSdkVersion 29 手动切换轮播图BUG

### ISSUE THREAD

**Issue by BayMaxM** [xiaohaibin/XBanner#185]
使用androidX 的时候，  手动切换轮播图，不能一下翻到下一个， 而是手指滑动多少就移动多少， 并且 pageChageListener也是失效,不能监听轮播图的改变，希望能看下，一下是项目用到的构建信息。希望androidX 的  能用sdk 29 以上的版本来实现
compileSdkVersion 29
buildToolsVersion "29.0.2"
 targetSdk  29
 dependencies {
        classpath "com.android.tools.build:gradle:4.0.0"
    }
gradle-6.1.1-all.zip

**Comment by xiaohaibin** [comment]
框架是啥版本，布局代码贴一下

**Comment by BayMaxM** [comment]
> 框架是啥版本，布局代码贴一下
 implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'androidx.core:core:1.3.1'
    implementation 'androidx.fragment:fragment:1.2.5'
    implementation 'androidx.annotation:annotation:1.1.0'
    implementation 'androidx.recyclerview:recyclerview:1.1.0'

implementation 'com.github.xiaohaibin:XBanner:androidx_v1.1.1'

<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/white"
    android:orientation="vertical">

    <include layout="@layout/appbar_main" />
    <com.stx.xhb.androidx.XBanner
        android:id="@+id/xbannImg"
        android:layout_width="match_parent"
        android:layout_height="200dp"
        app:AutoPlayTime="3000"
        app:isShowIndicatorOnlyOne="true"
        app:isShowNumberIndicator="false"
        app:pageChangeDuration="300"
        app:pointNormal="@drawable/point_normal"
        app:pointSelect="@drawable/point_now"
        app:pointsPosition="CENTER"
        app:tipTextSize="12sp" />
    <com.scwang.smart.refresh.layout.SmartRefreshLayout
        android:id="@+id/mainSmartRefresh"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical">

            <androidx.recyclerview.widget.RecyclerView
                android:id="@+id/rvMainRecycler"
                android:layout_width="match_parent"
                android:layout_height="match_parent" />

        </LinearLayout>

        <com.scwang.smart.refresh.footer.ClassicsFooter
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
    </com.scwang.smart.refresh.layout.SmartRefreshLayout>
</LinearLayout>

private XBanner xbannImg;
        xbannImg.loadImage(new XBanner.XBannerAdapter() {
            @Override
            public void loadBanner(XBanner banner, Object model, View view, int position) {
                ImageBean imageBean = (ImageBean) model;
                Glide.with(MainActivity.this).
                        load(imageBean.getImgUrl()).
                        placeholder(R.drawable.ic_launcher_background).
                        into((ImageView) view);
            }
        });
我放到了刷新控件外面试的，是在activity 里面。 布局应该没问题，其它是正常， 就是手动切换的时候不行。我sdk 是29以上的 还有我想问一下 如果是网络图片，图片每次chang 的时候   这个 loadBanner 每次调用都会加载一次网络图片么？

**Comment by xiaohaibin** [comment]
loadbanner就是回调当前的图片地址，图片加载就是看你使用图片加载框架，正常加载一次，再次加载就是使用缓存的了。
切换图片，你试过跑一下demo么

**Comment by xiaohaibin** [comment]
请更新到最新的版本，已修复
