### ISSUE TITLE
当只有三张图片时使用一屏显示多个模式模式时，右边的图片不显示的问题有遇到过吗

### ISSUE THREAD

**Issue by yuanqiuhu** [xiaohaibin/XBanner#187]
<com.stx.xhb.androidx.XBanner
        android:id="@+id/x_banner"
        android:layout_width="match_parent"
        android:layout_height="200dp"
        android:layout_alignParentTop="true"
        app:isClipChildrenMode="true"
        app:isClipChildrenModeLessThree="true"
        app:bannerBottomMargin="15dp"
        app:pointNormal="@mipmap/banner_no_select"
        app:pointSelect="@mipmap/banner_select"
        />

 //放图片地址的集合
        list_path = new ArrayList<>();
        list_path.add(R.mipmap.banner1);
        list_path.add(R.mipmap.banner2);
        list_path.add(R.mipmap.banner3);
        list_path.add(R.mipmap.banner1);
        xBanner.setData(list_path,null);
        xBanner.setPointsIsVisible(true);
        xBanner.setPointPosition(XBanner.CENTER);
        xBanner.setAutoPalyTime(3000);
        xBanner.loadImage(new XBanner.XBannerAdapter() {
            @Override
            public void loadBanner(XBanner banner, Object model, View view, int position) {
                Glide.with(getActivity()).load(list_path.get(position)).into((ImageView)view);
            }
        });

**Comment by xiaohaibin** [comment]
本地图片3张的时候确实会有这个情况，主要是由于viewpager 默认缓存导致

**Comment by Mrluosheng** [comment]
我发现，1.6.4版本没有这个bug

**Comment by yuanqiuhu** [comment]
试了一下，1.6.4版本的确实不会出现

**Comment by liming19981006** [comment]
androidx怎么办呢

**Comment by xiaohaibin** [comment]
已修复。普通版本请更新到1.8.0 Androidx更新1.1.3
