### ISSUE TITLE
作者你好，我遇到一个问题，如果场景是：后端给的图都是直角边的长方形图，但是产品要求都是圆角，圆角自己处理

### ISSUE THREAD

**Issue by binbinyYang** [xiaohaibin/XBanner#189]
作者你好，我遇到一个问题，如果场景是：后端给的图都是直角边的长方形图，但是产品要求都是圆角，圆角自己处理，我通过看你的源码发现你有一个XBanner里面setBannerPlaceholderDrawable 这个方法，以后能给一个公共的来修改或者替换占位图的方法吗

**Comment by xiaohaibin** [comment]
可以哈

**Comment by binbinyYang** [comment]
什么时候会提供

**Comment by xiaohaibin** [comment]
抱歉处理的晚，新版本已经提供

**Comment by binbinyYang** [comment]
你好 需要如何处理，有api 吗？

**Comment by xiaohaibin** [comment]
setBannerPlaceholderDrawable

**Comment by binbinyYang** [comment]
感谢
