### ISSUE TITLE
viewpager嵌套Xbanner滑动事件有冲突

### ISSUE THREAD

**Issue by chen3441251** [xiaohaibin/XBanner#197]
外层禁止滑动，但是xbanner需要滑动，是不是需要xbanner的viewpager事件分发

**Comment by chen3441251** [comment]
试了一下，support版本是ok的，Androidx版本不行，是分支代码没同步吗

**Comment by xiaohaibin** [comment]
代码是同步了的

**Comment by chen3441251** [comment]
> 代码是同步了的

那就奇怪了，我的步骤是（1）用了Androidx远程依赖，发现viewpager嵌套XBanner有滑动冲突，（2）下载了master分支源码，本地依赖是ok的（master应该是support的），然后切换回Androidx远程依赖又有冲突了，所以认为是两个分支可能没同步。明天有空我再对比找一下异同，今天暂时用了support远程依赖。

**Comment by xiaohaibin** [comment]
也有可能androidx包里面的viewpager版本问题
