### ISSUE TITLE
滑动很慢 导致崩了

### ISSUE THREAD

**Issue by alucard263096** [xiaohaibin/XBanner#210]
http://applinkupload.oss-cn-shenzhen.aliyuncs.com/alucard263096/aocean/pagehome/ac9d1d1b628c10c45b8a9338d5ba545d_211124161325_844695218.mp4

android 8.0，代码几乎和你demo的一模一样，用了glide加载

**Comment by xiaohaibin** [comment]
版本多少，看视频是ANR，看能不能把anr日志贴出来看下

**Comment by alucard263096** [comment]
implementation 'com.github.xiaohaibin:XBanner:1.8.3'
    
    这个版本，ANR怎么贴日志，给点提示大哥

**Comment by xiaohaibin** [comment]
AS 中的logcat会有打印

**Comment by xiaohaibin** [comment]
目前新版本是1.8.4

**Comment by alucard263096** [comment]
原来你说的是ANR是指安卓，哈哈，不过logcat里面我根据xbanner过滤，没有任何信息，然后error里面也没有，但是程序出现没有响应而崩溃了，我试一下1.8.4

**Comment by alucard263096** [comment]
这个测试的重点是两只手指都放在屏幕上

**Comment by alucard263096** [comment]
好的，我再试试

**Comment by xiaohaibin** [comment]
无反馈，暂时close
