### ISSUE TITLE
如何设置整个banner的圆角呢？

### ISSUE THREAD

**Issue by githeer** [xiaohaibin/XBanner#211]
如果自定义图片控件设置了圆角，但是在滑动时，四个角还是直角。滑动完变成圆角，很怪异

**Comment by githeer** [comment]
![1640241898(1)](https://user-images.githubusercontent.com/10293741/147199849-f97bc488-d853-4998-b0ef-e41a7a13b418.png)
能滑动时，也是圆角吗，自定义viewpager里 draw绘制下

**Comment by xiaohaibin** [comment]
看下你自定义布局代码，圆角  框架这边是没处理的，都是根据自己自定义布局

**Comment by githeer** [comment]
我是glide加载网络图代码设置圆角，其实不管是用imageview圆角控件或者代码设置圆角，都会在滑动的时候banner显示的是直角，能加个方法来设置整个banner为圆角吗

**Comment by githeer** [comment]
![image](https://user-images.githubusercontent.com/10293741/147202010-e78f403d-de18-4831-9f07-a98436f66e62.png)
滑动时，两边是直角

**Comment by xiaohaibin** [comment]
另外一边不是还没出来么
