### ISSUE TITLE
需求 如果集合只有一张图片也要进行轮播效果，请问有吗？

### ISSUE THREAD

**Issue by H-PeiXin** [xiaohaibin/XBanner#212]

**Comment by xiaohaibin** [comment]
支持的

**Comment by H-PeiXin** [comment]
怎么 没有找到这个方法呢

**Comment by H-PeiXin** [comment]
您的这个轮播图的选择器是否可以单独使用 需求需要一个只要你这种选择器样式来和Viewoager联动

**Comment by xiaohaibin** [comment]
框架的指示器只是一个简单的指示器，没有抽取出来

**Comment by H-PeiXin** [comment]
支持一张图也循环轮播的方法在哪

**Comment by xiaohaibin** [comment]
稍等，我没开放出来，一会更新出来

**Comment by H-PeiXin** [comment]
新改的setBannerData方法 两个参数 应该填什么

**Comment by xiaohaibin** [comment]
//setData（）方法已过时，推荐使用setBannerData（）方法，具体参照demo使用
  mXBanner.setBannerData(R.layout.image_fresco,“加载数据集合”);

看下demo

**Comment by xiaohaibin** [comment]
单张图片轮播已支持，请更新版本

**Comment by H-PeiXin** [comment]
之前用的 1.6.1'版本的 更新到哪个版本 更新之后不会报错吗  是在哪里新加了什么属性吗

**Comment by xiaohaibin** [comment]
普通版本  1.8.6   Androidx版本 1.2.3 ，不用加属性，更新代码自动会处理

**Comment by xiaohaibin** [comment]
注意看文档，这些东西在ReadMe都有的

**Comment by H-PeiXin** [comment]
好的 谢谢

**Comment by xiaohaibin** [comment]
issue 已处理，我就先关闭了
