### ISSUE TITLE
一屏多显动画问题

### ISSUE THREAD

**Issue by maomao-creat** [xiaohaibin/XBanner#214]
1.9.0
一屏多显模式是不支持设置动画吗，xBanner.setPageTransformer(new ZoomPageTransformer());设置了感觉没有啥效果

**Comment by xiaohaibin** [comment]
支持，设置动画方式要在setBannerData之后
mBanner.setBannerData(R.layout.layout_fresco_imageview, data);
mBanner.setPageTransformer(Transformer.Default);

**Comment by maomao-creat** [comment]
已解决，谢谢
