### ISSUE TITLE
开启自动轮播，会显示空白

### ISSUE THREAD

**Issue by greatflag** [xiaohaibin/XBanner#22]
APP用的微信那种布局，底部是bottom navi bar，MainActivity放Viewpager，然后放了四个Fragment。每当点到第四页，再回到首页。banner自动轮播下一张就显示空白页。然后下拉刷新，重新加载页面也出不来了。禁止掉自动轮播，就没这个问题。

**Comment by xiaohaibin** [comment]
首页代码贴出来看下，我在项目中使用暂未发现这样的情况，可以自己先试着找下原因

**Comment by greatflag** [comment]
真的很诡异的问题，之前两个月一直好好的，昨天测试说有BUG，我自己也能重现。debug发现不出哪里出错。但是每次点击第四页就出现，现在我viewpager的OffscreenPageLimit设置成3，暂时没了。。

**Comment by wtus** [comment]
的确在fragment 中会问题

**Comment by bunny-pu** [comment]
> 真的很诡异的问题，之前两个月一直好好的，昨天测试说有BUG，我自己也能重现。debug发现不出哪里出错。但是每次点击第四页就出现，现在我viewpager的OffscreenPageLimit设置成3，暂时没了。。

请问怎么解决的，我也是偶现这样的情况，oppo A37m特别容易出现

**Comment by orangeju1994** [comment]
> > 真的很诡异的问题，之前两个月一直好好的，昨天测试说有BUG，我自己也能重现。debug发现不出哪里出错。但是每次点击第四页就出现，现在我viewpager的OffscreenPageLimit设置成3，暂时没了。。
> 
> 请问怎么解决的，我也是偶现这样的情况，oppo A37m特别容易出现

好烦。。最近我的也是，在fragment中Xbanner作为RecyclerView的一个itemView，如果setAutoPlayAble为true就会经常空白（4张图基本只有第一张正常显示），设置为false，4张图片都正常显示。。。急死我了

**Comment by xiaohaibin** [comment]
设置一下预加载




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2020年04月23日 20:54，努力的橘子 写道：

真的很诡异的问题，之前两个月一直好好的，昨天测试说有BUG，我自己也能重现。debug发现不出哪里出错。但是每次点击第四页就出现，现在我viewpager的OffscreenPageLimit设置成3，暂时没了。。

请问怎么解决的，我也是偶现这样的情况，oppo A37m特别容易出现

好烦。。最近我的也是，在fragment中Xbanner作为RecyclerView的一个itemView，如果setAutoPlayAble为true就会经常空白（4张图基本只有第一张正常显示），设置为false，4张图片都正常显示。。。急死我了

**Comment by orangeju1994** [comment]
> 设置一下预加载 | | 萧海斌 邮箱：xhb_199409@163.com | 签名由 网易邮箱大师 定制 在2020年04月23日 20:54，努力的橘子 写道： 真的很诡异的问题，之前两个月一直好好的，昨天测试说有BUG，我自己也能重现。debug发现不出哪里出错。但是每次点击第四页就出现，现在我viewpager的OffscreenPageLimit设置成3，暂时没了。。 请问怎么解决的，我也是偶现这样的情况，oppo A37m特别容易出现 好烦。。最近我的也是，在fragment中Xbanner作为RecyclerView的一个itemView，如果setAutoPlayAble为true就会经常空白（4张图基本只有第一张正常显示），设置为false，4张图片都正常显示。。。急死我了 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

请问预加载是怎么操作的？

**Comment by xiaohaibin** [comment]
参考上面的做法




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2020年04月24日 09:45，努力的橘子 写道：

设置一下预加载 | | 萧海斌 邮箱：xhb_199409@163.com | 签名由 网易邮箱大师 定制 在2020年04月23日 20:54，努力的橘子 写道： 真的很诡异的问题，之前两个月一直好好的，昨天测试说有BUG，我自己也能重现。debug发现不出哪里出错。但是每次点击第四页就出现，现在我viewpager的OffscreenPageLimit设置成3，暂时没了。。 请问怎么解决的，我也是偶现这样的情况，oppo A37m特别容易出现 好烦。。最近我的也是，在fragment中Xbanner作为RecyclerView的一个itemView，如果setAutoPlayAble为true就会经常空白（4张图基本只有第一张正常显示），设置为false，4张图片都正常显示。。。急死我了 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

请问预加载是怎么操作的？

**Comment by lu769257351** [comment]
> 参考上面的做法| | 萧海斌邮箱：xhb_199409@163.com | 签名由网易邮箱定制 在2020年04月24日09:45，努力的橘子大师留言： 设置一下预加载 | | 萧海斌邮箱：xhb_199409@163.com | 签名由网易邮箱定制 2020年04月23日20:54，努力的橘子大师题词： 很很诡异的问题，之前真的一直说有BUG，我昨天自己能重现。debug发现不出哪里出错。但是每次点击第四页就出现，现在我viewpager的OffscreenPageLimit设置成3，暂时没了。好烦。 。。。急死我了——你收到这个是因为你发表了评论。直接回复此邮件，在 GitHub 上查看，或取消订阅。好像预加载是怎么操作的？ — 你收到这个是因为你发表了评论。直接回复此邮件，在 GitHub 上查看，或取消订阅。

我这边设置了预加载也存在同样的问题，同样是在fragment的recyclerview中
