### ISSUE TITLE
XBanner在AndroidX工程中使用的问题请教【急-在线等】

### ISSUE THREAD

**Issue by luqiming666** [xiaohaibin/XBanner#226]
我在我的AndroidX工程中引入时碰到了问题：
1. 我在build.gradle中已加入：implementation 'com.github.xiaohaibin:XBanner:androidx_v1.2.8'
2. 在louout xml中加入组件时却无法识别：
<com.stx.xhb.xbanner.XBanner
    android:id="@+id/banner

<img width="363" alt="xbanner_error" src="https://user-images.githubusercontent.com/97005447/180628444-cedb3324-fea4-4fcd-b3ee-96eb65b1aa6d.png">
"

**Comment by xiaohaibin** [comment]
androidx的包名路径是：com.stx.xhb.androidx.XBanner

**Comment by luqiming666** [comment]
已解决。非常感谢！
