### ISSUE TITLE
在recyclerview 的position ==0的位置时出现异常

### ISSUE THREAD

**Issue by leojiao123** [xiaohaibin/XBanner#26]
xbanner在recyclerview 的position为0的位置时，后台添加图片时会发生白屏，图片不显示
具体表现为图片一闪而过，然后banner白屏

**Comment by xiaohaibin** [comment]
position为0的位置?你是把xbanner放在recycleview头部么，可否贴下详细代码，因为我在项目也是添加在头部使用，正常显示图片。

**Comment by leojiao123** [comment]
就是将xbanner 写在了recyclerview  的 adapter里面 ，用的是可上拉加载的recyclerview   https://github.com/NEYouFan/ht-refreshrecyclerview 可能这个原因，不是原生的recyclerView 不兼容？
