### ISSUE TITLE
找不到类

### ISSUE THREAD

**Issue by tristanWong** [xiaohaibin/XBanner#29]
按照步骤：
1.添加Gradle依赖

dependencies {
    compile 'com.xhb:xbanner:latestVersion'//将latestVersion替换成上面最新的版本号
    compile 'com.nineoldandroids:library:2.4.0'
}
2.在清单文件中添加网络权限

<uses-permission android:name="android.permission.INTERNET" />
3.在布局文件中添加XBanner

    <com.stx.xhb.xbanner.XBanner
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:id="@+id/banner_1"
        android:layout_width="match_parent"
        android:layout_height="180dp"
        app:AutoPlayTime="3000"
        app:pointsContainerBackground="#44aaaaaa"
        app:pointNormal="@drawable/shape_noraml"
        app:pointSelect="@drawable/shape_selected"
        app:pointsPosition="RIGHT"
        app:tipTextSize="12sp"
        app:isShowNumberIndicator="true"
        app:isShowIndicatorOnlyOne="true"
        app:pageChangeDuration="800"/>

图片资源也增加进去了，运行后，闪退，错误：
 android.view.InflateException: Binary XML file line #14: Error inflating class com.stx.xhb.mylibrary.XBanner
是否是类变了？

**Comment by tristanWong** [comment]
说明： 
    compile 'com.xhb:xbanner:1.2.7'
    compile 'com.nineoldandroids:library:2.4.0' gradle运行也没有错误。

**Comment by xiaohaibin** [comment]
你在布局文件中输入xbanner

**Comment by ZhaoYidong** [comment]
如果你导入的是androidx 的依赖，布局应该用： com.stx.xhb.androidx.XBanner
