### ISSUE TITLE
最新版本依赖不了

### ISSUE THREAD

**Issue by jiangzx1990** [xiaohaibin/XBanner#31]
hi，1.2.8版本依赖不了
compile 'com.xhb:xbanner:1.2.8'
换成compile 'com.xhb:mylibraryr:1.2.8' 也不行

**Comment by xiaohaibin** [comment]
你再试下呢？或者暂时直接倒入依赖包

**Comment by yeaper** [comment]
1.2.8依赖不了，是放在哪个仓库了？

**Comment by xiaohaibin** [comment]
不好意思，这次更新不知道把名字改了 compile 'com.xhb:mylibrary:latestVersion'

**Comment by yeaper** [comment]
还是依赖不了，而且在Android 5.1系统上，1.2.7的版本会出现轮播一会，出现空白页

**Comment by xiaohaibin** [comment]
你再试下看看呢，我在demo上试了一下是可以依赖的
