### ISSUE TITLE
向前翻图片的时候，有空白图片的问题

### ISSUE THREAD

**Issue by jjhlzn** [xiaohaibin/XBanner#37]
![image](https://user-images.githubusercontent.com/4675776/38163320-abc93d14-3524-11e8-8416-b91c309aa047.png)

**Comment by gs2015** [comment]
1.3.2有问题  1.3.1没有问题

**Comment by xiaohaibin** [comment]
好的，我修复下

**Comment by ReStiller** [comment]
@xiaohaibin 确认有此问题，会导致ANR。

**Comment by xiaohaibin** [comment]
@ReStiller 方便贴下代码，我方便查找问题

**Comment by ReStiller** [comment]
@xiaohaibin 这是我在您的sample上所改动的内容
`private void RequestData() {
        mOthersList.add("https://i0.hdslb.com/bfs/bangumi/a47461859454493dfb20c2f6c00f2d71f601a215.jpg@2320w_664h.jpg");
        mOthersList.add("https://i0.hdslb.com/bfs/bangumi/97544754a61827dedce7d99015e0acd7f957e326.jpg@2320w_664h.jpg");
        List<String> tips = new ArrayList<>();
        tips.add("bilibili");
        tips.add("哔哩哔哩");
        mXBanner.setData(mOthersList, tips);
        mXBanner.setData(R.layout.xbanner_item_image, mOthersList, tips);
    }`
没有请求，直接填的数据
布局上针对属性也做了改动
`<com.stx.xhb.xbanner.XBanner
            xmlns:app="http://schemas.android.com/apk/res-auto"
            android:id="@+id/xbanner"
            android:layout_width="match_parent"
            android:layout_height="180dp"
            app:AutoPlayTime="3000"
            app:pointsVisibility="false"
            app:isAutoPlay="true"
            app:isHandLoop="false"
            app:isShowNumberIndicator="true"
            app:isShowIndicatorOnlyOne="true"
            app:pageChangeDuration="1000"/>`

**Comment by ReStiller** [comment]
@xiaohaibin 我不确认是否只有两张图片时才有这个问题，我目前就试了这个

**Comment by xiaohaibin** [comment]
已修复，版本体现1.3.4
