### ISSUE TITLE
自定义状态点如果两种状态点的大小不同，会有问题

### ISSUE THREAD

**Issue by AnotherJack** [xiaohaibin/XBanner#39]
point_select.xml
`<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android">
    <solid android:color="#f55a45" />
    <size
        android:width="8dp"
        android:height="4dp" />
    <corners android:radius="4dp" />
</shape>`

point_normal.xml
`<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android">
    <solid android:color="#d8d8d8" />
    <size
        android:width="4dp"
        android:height="4dp" />
    <corners android:radius="4dp" />
</shape>`

不同状态点切换的时候，大小不会改变，只会维持初始状态的尺寸，然后指示点会缩放

**Comment by yonglf** [comment]
我的也会这样 请问你解决了吗

**Comment by yuxuelian** [comment]
我也是   正打算提issues呢   发现已经有人提了
![image](https://user-images.githubusercontent.com/19601192/46673078-8ef61a80-cc0b-11e8-95e5-b72cce433f84.png)

**Comment by xiaohaibin** [comment]
这个bug是由于selector引起的，正在解决中。。。

**Comment by xiaohaibin** [comment]
该bug已解决，请更新版本至1.5.1，由于近期jcenter无法更新版本，请切换Jitpack方式引入，项目中使用方式不变，具体请看文档
