### ISSUE TITLE
点击时，能回传一个当前被点击的View不

### ISSUE THREAD

**Issue by bluebupang** [xiaohaibin/XBanner#41]
if (mOnItemClickListener != null && !mDatas.isEmpty()) {
                view.setOnClickListener(new OnDoubleClickListener() {
                    @Override
                    public void onNoDoubleClick(View v) {
                        mOnItemClickListener.onItemClick(XBanner.this, view,mDatas.get(realPosition), realPosition);
                    }
                });
}

希望大佬能给加一下哈

**Comment by xiaohaibin** [comment]
可以哈

**Comment by xiaohaibin** [comment]
已经加上，请更新版本1.4.1

**Comment by bluebupang** [comment]
好的多谢哈
