### ISSUE TITLE
在xbanner作为adapter的一个itemview时，不自动轮播

### ISSUE THREAD

**Issue by JsonDing** [xiaohaibin/XBanner#43]

**Comment by xiaohaibin** [comment]
是Listview、RecyclerView的Adapter？可以的话，请贴出代码，demo中也是这样使用的，还未出现这种情况

**Comment by JsonDing** [comment]
override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): RecyclerView.ViewHolder {
        when (viewType) {
            ITEM_TYPE_BANNER -> return BannerViewHolder(
                    inflater.inflate(R.layout.banner_item, parent, false))
            ITEM_TYPE_NEWS -> return NewsViewHolder(
                    inflater.inflate(R.layout.item_news_view, parent, false))
            ITEM_TYPE_BRANDS -> return BrandsViewHolder(
                    inflater.inflate(R.layout.item_brands_view, parent, false))
            else  -> return IntroViewHolder(
                    inflater.inflate(R.layout.item_goods_intro_view, parent, false))
        }
    }

<com.stx.xhb.xbanner.XBanner
        android:id="@+id/xBanner"
        android:layout_width="match_parent"
        android:layout_height="@dimen/qb_px_174"
        android:background="@color/common_white"
        app:AutoPlayTime="4000"
        app:isAutoPlay="true"
        app:isShowIndicatorOnlyOne="false"
        app:isShowNumberIndicator="false"
        app:pageChangeDuration="1000"
        app:pointNormal="@drawable/circle_gray"
        app:pointSelect="@drawable/circle_orange"
        app:pointsPosition="CENTER"
        app:pointsVisibility="true" />
