### ISSUE TITLE
一屏多个模式出现的问题

### ISSUE THREAD

**Issue by bluebupang** [xiaohaibin/XBanner#50]
rt，一屏多个模式 实现方式
1、通过setClipChildren和左右margin的方法是没有问题的，但是有一点用户体验问题，就是两边露出的item不能触摸滑动，故采用设置padding值的方法
2、通过setClipToPadding和左右padding的方法，在item个数为2或3时，出现了问题，右边的item显示不全，如图
![20181012142118](https://user-images.githubusercontent.com/15033191/46851512-53856700-ce2a-11e8-92d9-dc12bf41e310.jpg)
![20181012142125](https://user-images.githubusercontent.com/15033191/46851514-53856700-ce2a-11e8-86ab-c8fc66c1042e.jpg)

求大佬解答，附上关键代码

mViewPager.setClipToPadding(false);
mViewPager.setPageMargin(mViewPagerMargin);
mViewPager.setPadding(mViewPagerMargin+mClipChildrenLeftRightMargin,0,mViewPagerMargin+mClipChildrenLeftRightMargin,0);

**Comment by xiaohaibin** [comment]
1、目前左右两边是拦截了触摸机制的，滑动的话通过滑动中间更大的地方不是更好么，我是这样理解的哈。
2、不要去设置ClipToPadding，setPadding这些，具体看下文档，有相关属性和方法提供的

**Comment by Mrluosheng** [comment]
我也碰到了通用的问题

**Comment by Mrluosheng** [comment]
我也碰到了同样的问题

**Comment by xiaohaibin** [comment]
更新最新版本即可
