### ISSUE TITLE
高度问题,为什么高度都是固定的??没有封装自适应

### ISSUE THREAD

**Issue by yy1033733525** [xiaohaibin/XBanner#52]

**Comment by xiaohaibin** [comment]
哪种模式的高度？一屏多显，一屏多显的两边的图片高度可以自定义，通过自定义切换动画可以实现，具体可以看下ScaleTransFromer这个类

**Comment by yy1033733525** [comment]
banner.setLayoutParams(linearParams); 这么设置的,能用

**Comment by xiaohaibin** [comment]
嗯，Xbanner没有写死高度的，你们都可以自定义，或者动态设置
