### ISSUE TITLE
禁止无限循环

### ISSUE THREAD

**Issue by LiuDongCai** [xiaohaibin/XBanner#53]
可以加一个方法吗，禁止无限循环的方法，因为有时候拿这个做引导页

**Comment by xiaohaibin** [comment]
可以添加的哈，目前布局中也可以禁止

**Comment by LiuDongCai** [comment]
如何禁止

**Comment by xiaohaibin** [comment]
![image](https://user-images.githubusercontent.com/11681218/47338321-f9a65c00-d6c9-11e8-91e0-70dcfa4127e0.png)

请看文档
