### ISSUE TITLE
一屏多模式效果

### ISSUE THREAD

**Issue by chenchali** [xiaohaibin/XBanner#55]
一瓶多模式效果--文字显示的时候跑到了图片的外边，还有能不能将指示器放到图片的下边不放到图片上

**Comment by xiaohaibin** [comment]
一屏多显模式，目前暂时不建议使用有文字的指示器

**Comment by chenchali** [comment]
那这个指示器能放到图片的下边吗？

**Comment by xiaohaibin** [comment]
目前不行哦，可以自己单独弄个指示器放在最下面

**Comment by xiaohaibin** [comment]
一屏多显模式支持将指示器设置在轮播区域下方了，具体参见demo和文档，版本 1.6.4
