### ISSUE TITLE
无论如何都不显示图片

### ISSUE THREAD

**Issue by Cazaea** [xiaohaibin/XBanner#58]
我用的MVVM框架，Databinding数据绑定，同时使用了RxJava2和RxAndroid，图片加载框架Glide，在你的Demo中使用的是Fresco，即使是Demo也无法显示图片，能把Demo先跑出图片吗？

我把XBanner放进了我的XRecyclerView的Header中，始终无法显示。

**Comment by xiaohaibin** [comment]
该框架跟你使用啥架构、框架无关，demo中是可以正常显示图片的，参照文档，检查网络、检查图片url、图片加载显示要自己实现loadImage（）方法进行加载。
