### ISSUE TITLE
自定义布局中包含recycleview，itemOnClick接收不到点击回调

### ISSUE THREAD

**Issue by jyshuai** [xiaohaibin/XBanner#59]

**Comment by xiaohaibin** [comment]
父布局加上click属性试试

**Comment by xiaohaibin** [comment]
android:clickable="true"
android:focusable="true"

**Comment by jyshuai** [comment]
这种方法已经试过了，依然不行，这两天项目要上线，等过两天我再好好研究一下。目前是在自定义布局里面的recycleview的item中监听了点击事件，然后回调到最外层，但是这样会导致监听区域变小，因为我的自定义布局里面还有其他图片，这个recycleview并不是填充整个布局。

**Comment by xiaohaibin** [comment]
我这边测试是可以的，你根布局加上以上两个属性之后，里面的子布局不要去添加了
