### ISSUE TITLE
一屏多模 添加到Recyclerview 

### ISSUE THREAD

**Issue by HoCham-Lu** [xiaohaibin/XBanner#61]
一屏多模 添加到Recyclerview 的头部的时候只显示负一屏，中间的没显示。 我换成普通模式 正常轮播，且一屏多模添加进RecyclerView的时候，滑动有点卡 换成普通的没问题

**Comment by xiaohaibin** [comment]
方便的话，可以贴个截图，数据是本地图片还是网络图片

**Comment by HoCham-Lu** [comment]
数据加载 网络图  是有数据的  我+ 你公众号 给你贴图

**Comment by xiaohaibin** [comment]
你加QQ群：271127803

**Comment by HoCham-Lu** [comment]
已经解决 谢谢，辛苦了
