### ISSUE TITLE
轮播图圆角的一个问题

### ISSUE THREAD

**Issue by darkrevier** [xiaohaibin/XBanner#65]
按照demo我用fresco加载网络3张图片设置圆角  但是出现了2张图片有圆角有一张没有圆角 不知道这是什么情况

**Comment by xiaohaibin** [comment]
自定义布局了么，一屏多显模式？正常情况不会出现这种，图片加载是fresco 处理，与框架本身无关，另外是否单独设置了切换动画

**Comment by darkrevier** [comment]
代码中设置了     xBanner.setPageTransformer(Transformer.Default);

**Comment by darkrevier** [comment]
目前不清楚到底是什么原因

**Comment by xiaohaibin** [comment]
一屏多显模式的话，代码中无须设置切换动画，默认有切换动画效果，切换动画会做图片缩放的效果
