### ISSUE TITLE
一屏多模式banner的position

### ISSUE THREAD

**Issue by darkrevier** [xiaohaibin/XBanner#67]
banner.loadImage(new XBanner.XBannerAdapter() {
            @Override
            public void loadBanner(XBanner banner, Object model, View view, int position) {
                Log.i("loadBanner", "loadBanner: "+position);
            }
        });
demo 中 这个position的数字与所展示对应图片位置不相同 这个是什么原因

**Comment by xiaohaibin** [comment]
你确定？手动还是自动，我本地测试是没遇到你这个情况

**Comment by darkrevier** [comment]
clipchildrenmode里面的banner position就是对应不上

**Comment by xiaohaibin** [comment]
一屏多显，loadbanner方法因为会提前预加载后面的图片，所以postion不能拿来判断，点击事件的postion是准确的

**Comment by xiaohaibin** [comment]
loadbanner中pos拿来加载图片是没问题的，打印跟自己看到的是不一样的是正常

**Comment by darkrevier** [comment]
那我自定义指示器怎么搞啊  取不到对应的position

**Comment by xiaohaibin** [comment]
你获取viewpager，监听viewpager的事件

**Comment by xiaohaibin** [comment]
直接通过下面的方法去监听：

mBanner.setOnPageChangeListener(new ViewPager.OnPageChangeListener() {
            @Override
            public void onPageScrolled(int i, float v, int i1) {

            }

            @Override
            public void onPageSelected(int i) {
                   Log.i("===>POS",i+"");
            }

            @Override
            public void onPageScrollStateChanged(int i) {

            }
        });

**Comment by xiaohaibin** [comment]
一屏多显模式支持将指示器设置在轮播区域下方了，具体参见demo和文档，版本 1.6.4
