### ISSUE TITLE
当viewpage被划出界面，出现的一些问题。

### ISSUE THREAD

**Issue by wo883721** [xiaohaibin/XBanner#7]
一.  当viewpage被划出界面，会出现页数一直停留在最后一页，当viewpage重新出现时，才会跳转第一页。
   这是因为在MyHandler的handleMessage方法的一个逻辑错误。我改动后的代码。
switch (msg.what) {
                case WHAT_AUTO_PLAY:
                    XBanner1 banner = mXBanner.get();
                    if (banner != null) {
//                        banner.mCurrentPositon++;
                        //这里不直接使用mCurrentPositon+1，主要是为了防止一种情况，当viewpage不在页面中显示，那么onPageScrollStateChanged方法有时候是不会回调的，
                        //那么当mCurrentPositon==banner.mModels.size() + 1的时候，就没有办法重新设置成1，这就会导致mCurrentPositon不断地自增，但是又不会回调OnPageChangeListener中任何方法，
                        //因为viewpage做了判断，当setCurrentItem方法设置的值item大于mAdapter.getCount()，就设为mAdapter.getCount()-1，所以导致item值都是mAdapter.getCount()-1，就不会回调OnPageChangeListener中任何方法。
                        //因此当banner.mCurrentPositon==banner.mModels.size() + 1，就重新设置为1.
                        banner.mCurrentPositon =  banner.mCurrentPositon % (banner.mModels.size() + 1) + 1;
                        banner.mViewPager.setCurrentItem(banner.mCurrentPositon);
                        banner.sendScrollMessage(banner.mAutoPalyTime);
                    }
                    break;
                default:
                    break;
            }

二.当viewpage被划出界面时，这时退出activity，onDetachedFromWindow()方法是没有回调的，这就导致stopAutoPlay()方法没有调用，handler还在定时操作，但是这时activity却已经销毁了，这是在调用XBannerAdapter的loadBanner就会导致程序崩溃。
  这可能是listview的原因。但是最后还是在activity的onStop()方法中调用stopAutoPlay()方法，这样保险些。

**Comment by xiaohaibin** [comment]
恩，谢谢你的提出的问题，我会在后续版本改进并提示各位开发者；
