### ISSUE TITLE
动态显示banner时崩溃

### ISSUE THREAD

**Issue by kindyrain** [xiaohaibin/XBanner#70]
banner数量动态添加时，如果开始数量是1，添加到数量是2的时候会崩溃  The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! 但是从2个再添加就没有问题

**Comment by kindyrain** [comment]
是从1个开始增加就有问题

**Comment by xiaohaibin** [comment]
我测试看下

**Comment by xiaohaibin** [comment]
版本号多少

**Comment by kindyrain** [comment]
1.6.1

**Comment by kindyrain** [comment]
for (final  Banner banner : mBannerList) {
                SimpleBannerInfo simpleBannerInfo = new SimpleBannerInfo() {
                    @Override
                    public Object getXBannerUrl() {
                        return banner.getImage();
                    }
                };
                imageUrlList.add(simpleBannerInfo);
            }

            bannerView.setBannerData(imageUrlList);
            bannerView.setAutoPlayAble(mBannerList.size() > 1);
            //加载banner图片
            bannerView.loadImage(new XBanner.XBannerAdapter() {
                @Override
                public void loadBanner(XBanner banner, Object model, View view, int position) {

                    //1、此处使用的 Glide 加载图片，可自行替换自己项目中的图片加载框架
                    //2、返回的图片路径为 Object 类型，你只需要强转成你传输的类型就行，切记不要胡乱强转！
                    Glide.with(context.get()).load(mBannerList.get(position).getImage())
                            .placeholder(R.mipmap.whole_defect_picture)
                            .error(R.mipmap.default_banner)
                            .into((ImageView) view);
                }
            });
            bannerView.setOnItemClickListener(new XBanner.OnItemClickListener() {
                @Override
                public void onItemClick(XBanner banner, Object model,View view, int position) {
                    onBannerListener.onItemClick(mBannerList.get(position), position);
                }
            });
            bannerView.setPageTransformer(Transformer.Scale);

**Comment by xiaohaibin** [comment]
我这没复现呢O__O "…

**Comment by kindyrain** [comment]
设置isHandleLoop属性后不出现崩溃

**Comment by kindyrain** [comment]
没有设置isHandleLoop属性会出现，崩溃设置为true后，就没有问题了，应该是哪里计算有问题，出错提示资源 ffffffff不存在

**Comment by kindyrain** [comment]
自动轮播的模式下，没有设置isHandLoop属性出问题，设置isHandLoop为true时没有问题

**Comment by xiaohaibin** [comment]
按照你的操作步骤，还是没有复现你的问题，另外你添加数据的方式有点不对，不必弄个循环这样添加，否则我新增的这个setBannerData（）方法就没意义了，建议参考demo使用

**Comment by kindyrain** [comment]
可能和打开aapt2编译方式有关。。不是要构造一个List<? extends SimpleBannerInfo> models吗？

**Comment by xiaohaibin** [comment]
是要呀，demo不是你这样使用

**Comment by bananaCaptain** [comment]
作者你好！我也出现了同样的报错，就是一开始加载了三张图片然后更新数据为只有一张图片，三张和一张切换时就会崩溃。isHandLoop设置为true就不会了！谢谢

**Comment by xiaohaibin** [comment]
版本是最新的么

**Comment by xiaohaibin** [comment]
方便的话，可以贴一下报错信息

**Comment by xiaohaibin** [comment]
setAutoPlayAble方法要在 setBannerData方法之前调用

**Comment by duxun** [comment]
> setAutoPlayAble方法要在 setBannerData方法之前调用

我这边做数据边更的时候 数据源从1变更到2的时候没有问题，但是数据源从2已变更到1的时候回报错 
 java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
我这边做了下判断
  xBanner.loadImage((banner, model, view, position) -> {
                if (position < stringList.size()) {
                    ImageView imageView = view.findViewById(R.id.banner_image);
                    GlideLoadUtil.loadImage(this, R.mipmap.ic_launcher_c, stringList.get(position).getXBannerUrl(), imageView);
                }
            });
但愿可以帮你
