### ISSUE TITLE
可见开始循环+隐藏停止循环

### ISSUE THREAD

**Issue by Cazaea** [xiaohaibin/XBanner#74]
可见开始循环+隐藏停止循环, 怎么处理, 目前在滚动RecyclerView时, 重新看到Banner, 会突然切换一个Image,   并不是平滑的自动轮播

**Comment by xiaohaibin** [comment]
因为在RecyclerView上会出现一个bug，造成重新看到banner时，banner卡住的问题，目前采用的解决方案会这样
