### ISSUE TITLE
分屏模式 原先两张图片 更新后台数据5张图片 刷新bug

### ISSUE THREAD

**Issue by Bob198809** [xiaohaibin/XBanner#80]
分屏模式 原先两张图片 更新后台数据5张图片 刷新bug
刷新后导致页面不显示  只能看到最左边的那张图   中间和右边的图都看不到

**Comment by xiaohaibin** [comment]
版本多少




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2019年02月15日 11:38，Bob198809 写道：

分屏模式 原先两张图片 更新后台数据5张图片 刷新bug
刷新后导致页面不显示 只能看到最左边的那张图 中间和右边的图都看不到

**Comment by Bob198809** [comment]
用的implementation 'com.xhb:xbanner:1.5.1'

**Comment by xiaohaibin** [comment]
版本到github查看最新版本使用




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2019年02月15日 12:48，Bob198809 写道：

用的implementation 'com.xhb:xbanner:1.5.1'
