### ISSUE TITLE
一屏多显问题

### ISSUE THREAD

**Issue by ncworm** [xiaohaibin/XBanner#81]
mBanner.setBannerData(R.layout.layout_fresco_imageview, bannerList);
当我设置R.layout.layout_fresco_imageview时banner是空白的。没走到loadImage的回调，不设置自定义imageview的时候直接mBanner.setBannerData(bannerList);就能显示，这是为什么呢？

**Comment by xiaohaibin** [comment]
参考demo，demo中有自定义布局的事例




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2019年03月02日 22:36，thornfish 写道：

mBanner.setBannerData(R.layout.layout_fresco_imageview, bannerList);
当我设置R.layout.layout_fresco_imageview时banner是空白的。没走到loadImage的回调，不设置自定义imageview的时候直接mBanner.setBannerData(bannerList);就能显示，这是为什么呢？

**Comment by ncworm** [comment]
恩，我看到了，就是不知道为什么集成进去就不行了，白屏，无法加载出来图片

**Comment by xiaohaibin** [comment]
正常使用一般是不会的，因为demo跑起来都是正常的，你查下代码呢

**Comment by ncworm** [comment]
恩，解决了。
