### ISSUE TITLE
一屏多显图片缩放的时候指示器,提示文字和图片效果分离

### ISSUE THREAD

**Issue by shenqiwen** [xiaohaibin/XBanner#82]
感谢作者的开源.

![@G3Y0F~$XO5M3T`73I8YDAW](https://user-images.githubusercontent.com/31466883/54331432-f0a43000-4654-11e9-883b-242bb0a9e560.png)

这钟动画切换的时候感觉不美观啊

**Comment by xiaohaibin** [comment]
指示器除非也做一个过渡效果，文字可以放在自定义布局，自己动态设置




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2019年03月14日 12:32，镜花水月 写道：

感谢作者的开源.

这钟动画切换的时候感觉不美观啊
