### ISSUE TITLE
边距问题

### ISSUE THREAD

**Issue by ncworm** [xiaohaibin/XBanner#84]
version：最新版            
            banner模式：mBanner2.setPageTransformer(Transformer.Default);
            当图片数量少于3张时
            app:clipChildrenLeftRightMargin="15dp"
            app:viewpagerMargin="15dp"
            这两个边距直接失效

**Comment by xiaohaibin** [comment]
少于三张，是不是自动恢复成普通模式了

**Comment by ncworm** [comment]
是的。内边距都消失了。横向直接填充满了整个屏幕，指示器的边距设置也失去作用

**Comment by ncworm** [comment]
![image](https://user-images.githubusercontent.com/10293741/54405998-5a830f00-4713-11e9-8704-e9984b8b2982.png)
![image](https://user-images.githubusercontent.com/10293741/54406005-5fe05980-4713-11e9-9ab1-865424c7aae1.png)

**Comment by ncworm** [comment]
![image](https://user-images.githubusercontent.com/10293741/54406042-8d2d0780-4713-11e9-8d74-66fb5119176f.png)
![image](https://user-images.githubusercontent.com/10293741/54406049-91f1bb80-4713-11e9-9eb2-6edc1068b433.png)

**Comment by xiaohaibin** [comment]
看下文档，有个属性可以设置的哈




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2019年03月15日 11:15，thornfish 写道：

**Comment by ncworm** [comment]
mBanner.setViewPagerMargin(15);
如果你是说这个的话，或者
            app:clipChildrenLeftRightMargin="15dp"
            app:viewpagerMargin="15dp"
这两个的话，我都已经设置过了没有效果

**Comment by Zhangxd77** [comment]
@githeer 请问后来你怎么弄了，我也是设置了没有用

**Comment by githeer** [comment]
> @githeer 请问后来你怎么弄了，我也是设置了没有用
你是女开发者？  app:isClipChildrenModeLessThree="true"     xml 加入这个就行了
