### ISSUE TITLE
是否可以设置禁止循环，可手动切换，但是没法循环

### ISSUE THREAD

**Issue by dary123** [xiaohaibin/XBanner#87]
是否可以设置禁止循环，可手动切换，但是没法循环

**Comment by xiaohaibin** [comment]
可以，有属性控制，具体看文档哈




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2019年03月18日 17:38，cool dog 写道：

是否可以设置禁止循环，可手动切换，但是没法循环
