### ISSUE TITLE
loadBanner方法中position位置疑问？？

### ISSUE THREAD

**Issue by 201216323** [xiaohaibin/XBanner#9]
@Override
    public void loadBanner(XBanner banner, View view, int position) {
        MyApplication.getImageLoader(mContext).displayImage(imgesUrl.get(position), (ImageView) view, MyApplication.getSimpleImageOptions());
        textViewDesciption.setText("position:"+position+"@"+"数据");
    }
上面是我加载数据，想问的是这里面的position是不是不对啊，我显示的是第一张图片position=1，我显示第二张图片position=0，（就2张图），这个position不应该是0  1  到list的Size啊？？

**Comment by xiaohaibin** [comment]
是图片显示不对么？你可以打印position看下

**Comment by 201216323** [comment]
图片的显示是正确的。打印position看了，我有两张图片，打印的position第一个是1第二个是0，因为我要在ViewPager切换的时候根据position，给TextView显示不同的数据。

**Comment by xiaohaibin** [comment]
你需要设置每张图片的文字描述目前不能这样使用哈，我最新的版本有添加这个功能，你可以看下我的demo
