### ISSUE TITLE
数字模式不可以设置数字的pedding

### ISSUE THREAD

**Issue by EiuaLee** [xiaohaibin/XBanner#92]
目前解决方法如下（有需求的同学）：
xml中自定义一个Textview用于显示当前的图片的数字标示 例如:
<FramLayout...
 <XBanner
     ...
     />
//自定义
<TextView
  android:id="@+id/tvBannerIndex"
  android:paddingLeft="@dimen/dp_5"
  android:paddingRight="@dimen/dp_5"
 ...
/>

<.../FramLayout>

具体实现：
 banner.setOnPageChangeListener(object : ViewPager.OnPageChangeListener {
            override fun onPageScrollStateChanged(p0: Int) {}
            override fun onPageScrolled(p0: Int, p1: Float, p2: Int) {}
            override fun onPageSelected(position: Int) {
                tvBannerIndex.setText("${(position % banner.realCount)+1}/${banner.realCount}")
            }
        })

**Comment by xiaohaibin** [comment]
这个其实可以通过设置数字的shape padding来实现，可以试试
