### ISSUE TITLE
Error:(183, 16) 错误: 无法访问ViewPager 找不到androidx.viewpager.widget.ViewPager的类文件

### ISSUE THREAD

**Issue by chenni521** [xiaohaibin/XBanner#93]
Error:(183, 16) 错误: 无法访问ViewPager
找不到androidx.viewpager.widget.ViewPager的类文件   你的类文件报错 咋解决啊

**Comment by xiaohaibin** [comment]
你是使用了androidx版本？

**Comment by chenni521** [comment]
对的 就是x版本




------------------ 原始邮件 ------------------
发件人: "Mr.XIAO"<notifications@github.com>;
发送时间: 2019年5月8日(星期三) 晚上6:18
收件人: "xiaohaibin/XBanner"<XBanner@noreply.github.com>;
抄送: "唐志津"<614233969@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [xiaohaibin/XBanner] Error:(183, 16) 错误: 无法访问ViewPager 找不到androidx.viewpager.widget.ViewPager的类文件 (#93)




你是使用了androidx版本？

**Comment by xiaohaibin** [comment]
使用androidx的话，项目要做如下配置：
![image](https://user-images.githubusercontent.com/11681218/57368530-e66a6200-71bd-11e9-8c01-1e2d1f41ce3f.png)

**Comment by chenni521** [comment]
好的 谢谢了  




------------------ 原始邮件 ------------------
发件人: "Mr.XIAO"<notifications@github.com>; 
发送时间: 2019年5月8日(星期三) 晚上6:20
收件人: "xiaohaibin/XBanner"<XBanner@noreply.github.com>; 
抄送: "唐志津"<614233969@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [xiaohaibin/XBanner] Error:(183, 16) 错误: 无法访问ViewPager 找不到androidx.viewpager.widget.ViewPager的类文件 (#93)




使用androidx的话，项目要做如下配置：
