### ISSUE TITLE
依赖报错

### ISSUE THREAD

**Issue by protectedMan** [xiaohaibin/XBanner#96]
![image](https://user-images.githubusercontent.com/17565737/57748205-83238700-770b-11e9-9daa-219edfd74bfa.png)
    api 'com.github.xiaohaibin:XBanner:androidx_v1.0.1'
依赖后运行就报错，还没有执行代码

**Comment by xiaohaibin** [comment]
![image](https://user-images.githubusercontent.com/11681218/57748510-db0ebd80-770c-11e9-8bab-1bd6f500ec34.png)

**Comment by protectedMan** [comment]
我自己的项目有androidx

**Comment by protectedMan** [comment]
我试了下 依赖 api 'com.github.xiaohaibin:XBanner:1.6.6'没问题，依赖
com.github.xiaohaibin:XBanner:androidx_v1.0.1 会出问题。
我自己的项目中
![image](https://user-images.githubusercontent.com/17565737/57748663-80c22c80-770d-11e9-838d-a8fd48a7f64e.png)

**Comment by xiaohaibin** [comment]
![image](https://user-images.githubusercontent.com/11681218/57750186-ceda2e80-7713-11e9-8b62-eb1602f142bb.png)
报错原因是这里，你参照修改一下你的主题

**Comment by protectedMan** [comment]
主题也确实是Theme.AppCompat 没有问题。只要依赖XBanner就报这个错

**Comment by xiaohaibin** [comment]
你把你的baseAct 换成继承androidx包下的AppCompat

**Comment by xiaohaibin** [comment]
https://blog.csdn.net/qq_17766199/article/details/81433706

**Comment by protectedMan** [comment]
我项目已经全面迁移到了androidx。依赖别的androidx的lib也没有问题。

**Comment by xiaohaibin** [comment]
好的，我查下原因
