### ISSUE TITLE
全屏显示banner，无法自适应宽高，图片会被拉伸

### ISSUE THREAD

**Issue by gkblack** [xiaohaibin/XBanner#97]

**Comment by xiaohaibin** [comment]
自定义布局，设置图片缩放类型

**Comment by gkblack** [comment]
自定义布局，旋转屏幕之后就变形了了，这个怎么解决呢

**Comment by xiaohaibin** [comment]
旋转屏幕变形？设置图片的缩放类型也这样？

**Comment by gkblack** [comment]
我是想屏幕旋转的时候他能自适应大小

**Comment by gkblack** [comment]
设置的是centerCrop就显示不全了

**Comment by xiaohaibin** [comment]
这个没法自适应大小，要么只显示原始分辨率的，除非你的图片分辨率跟手机屏幕一致

**Comment by gkblack** [comment]
![C63AA61B2F810F1A20493CDDA5D6D598](https://user-images.githubusercontent.com/17800211/57901605-6ec0c500-7898-11e9-9470-72bee22b7cdc.png)
![Uploading 6E5BA751E873744F7FCC8B2EEA08D1A7.png…]()
我是想像这样显示图片

**Comment by gkblack** [comment]
我用glide加载网络图片能这样显示，但加载本地图片就不行了，不知道为什么

**Comment by gkblack** [comment]
![image](https://user-images.githubusercontent.com/17800211/57901743-e393ff00-7898-11e9-83e8-b5e150cf7786.png)
我是这么写的，加载网络图片是可以的，但到了获取本地图片就不行了，会变形，这个方法没起作用

**Comment by gkblack** [comment]
可以了，是我傻了，重新定义下imagview就好了，谢谢
